// MIT validation host, original NVIDIA device functions included unchanged.
#include <cuda_runtime.h>
#include <helper_math.h>
#include <helper_image.h>
#include <vector>
#include <cstdio>
typedef unsigned char uchar;
#include "bicubic-texture-kernel.cuh"
#define CHECK(x) do{auto e=(x);if(e!=cudaSuccess){printf("CUDA ERROR %s\n",cudaGetErrorString(e));return 2;}}while(0)
int main(){const int widths[]={35,128,512},heights[]={19,96,512};const float scales[]={.75f,3.25f,.35f},txs[]={-.3125f,-10.375f,0},tys[]={.625f,-20.625f,0},cxs[]={8,64,256},cys[]={6,48,256};for(int scenario=0;scenario<3;scenario++){int w=widths[scenario],h=heights[scenario],tw=scenario?512:16,th=scenario?512:12;std::vector<uchar> pixels(tw*th);if(!scenario)for(int i=0;i<tw*th;i++)pixels[i]=64+(i*37)%128;else{uchar* data=nullptr;unsigned pw,ph;if(!sdkLoadPGM("showcases/texture2d/teapot512.pgm",&data,&pw,&ph)||pw!=tw||ph!=th)return 2;std::copy(data,data+tw*th,pixels.begin());free(data);}cudaArray_t array;auto channel=cudaCreateChannelDesc<uchar>();CHECK(cudaMallocArray(&array,&channel,tw,th));CHECK(cudaMemcpy2DToArray(array,0,0,pixels.data(),tw,tw,th,cudaMemcpyHostToDevice));cudaResourceDesc resource={};resource.resType=cudaResourceTypeArray;resource.res.array.array=array;std::vector<unsigned> result(w*h+16,0xdeadbeef);uchar4* output;CHECK(cudaMalloc(&output,result.size()*4));for(int mode=0;mode<5;mode++){CHECK(cudaMemcpy(output,result.data(),result.size()*4,cudaMemcpyHostToDevice));cudaTextureDesc desc={};desc.filterMode=(mode==1||mode==3)?cudaFilterModeLinear:cudaFilterModePoint;desc.addressMode[0]=desc.addressMode[1]=cudaAddressModeClamp;desc.readMode=cudaReadModeNormalizedFloat;cudaTextureObject_t tex;CHECK(cudaCreateTextureObject(&tex,&resource,&desc,nullptr));dim3 block(8,8),grid((w+7)/8,(h+7)/8);
#define ARGS output,w,h,txs[scenario],tys[scenario],scales[scenario],cxs[scenario],cys[scenario],tex
switch(mode){case 0:case 1:d_render<<<grid,block>>>(ARGS);break;case 2:d_renderBicubic<<<grid,block>>>(ARGS);break;case 3:d_renderFastBicubic<<<grid,block>>>(ARGS);break;case 4:d_renderCatRom<<<grid,block>>>(ARGS);break;}
CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());CHECK(cudaMemcpy(result.data(),output,result.size()*4,cudaMemcpyDeviceToHost));for(int i=w*h;i<w*h+16;i++)if(result[i]!=0xdeadbeef)return 1;for(int i=0;i<w*h;i++)if((result[i]>>24)!=0)return 1;char path[128];snprintf(path,sizeof(path),"reports/bicubic-texture-native-%d-%d.bin",scenario,mode);FILE* f=fopen(path,"wb");if(!f||fwrite(result.data(),4,result.size(),f)!=result.size())return 2;fclose(f);CHECK(cudaDestroyTextureObject(tex));printf("scenario=%d mode=%d %dx%d native output captured; alpha and guards PASS\n",scenario,mode,w,h);}CHECK(cudaFree(output));CHECK(cudaFreeArray(array));}return 0;}
