// MIT validation host; original NVIDIA kernel and original BMP loader.
#include <cuda_runtime.h>
#include <helper_math.h>
#include <vector>
#include <cstdio>
#include <cmath>
#include "bilateral-filter-kernel.cuh"
extern "C" void LoadBMPFile(uchar4**,unsigned*,unsigned*,const char*);
#define CHECK(x) do{auto e=(x);if(e!=cudaSuccess){printf("CUDA ERROR %s\n",cudaGetErrorString(e));return 2;}}while(0)
int main(){const int ws[]={17,31,640},hs[]={9,19,480},rs[]={0,2,5};const float deltas[]={4,2,4},ranges[]={.1,.25,.1};for(int k=0;k<3;k++){int w=ws[k],h=hs[k],r=rs[k];std::vector<uchar4> pixels(w*h);if(k==2){uchar4* data=nullptr;unsigned pw,ph;LoadBMPFile(&data,&pw,&ph,"showcases/bilateral-filter/nature.bmp");if(!data||pw!=w||ph!=h)return 2;std::copy(data,data+w*h,pixels.begin());free(data);}else for(int i=0;i<w*h;i++)pixels[i]=make_uchar4((i*37)%256,(i*37+73)%256,(i*37+146)%256,0);float weights[64]={};for(int i=0;i<2*r+1;i++)weights[i]=expf(-float((i-r)*(i-r))/(2*deltas[k]*deltas[k]));CHECK(cudaMemcpyToSymbol(cGaussian,weights,sizeof(weights)));cudaArray_t array;auto channel=cudaCreateChannelDesc<uchar4>();CHECK(cudaMallocArray(&array,&channel,w,h));CHECK(cudaMemcpy2DToArray(array,0,0,pixels.data(),w*4,w*4,h,cudaMemcpyHostToDevice));cudaResourceDesc res={};res.resType=cudaResourceTypeArray;res.res.array.array=array;cudaTextureDesc desc={};desc.filterMode=cudaFilterModePoint;desc.addressMode[0]=desc.addressMode[1]=cudaAddressModeClamp;desc.readMode=cudaReadModeNormalizedFloat;cudaTextureObject_t tex;CHECK(cudaCreateTextureObject(&tex,&res,&desc,nullptr));std::vector<unsigned> result(w*h+16,0xdeadbeef);unsigned* output;CHECK(cudaMalloc(&output,result.size()*4));CHECK(cudaMemcpy(output,result.data(),result.size()*4,cudaMemcpyHostToDevice));d_bilateral_filter<<<dim3((w+7)/8,(h+7)/8),dim3(8,8)>>>(output,w,h,ranges[k],r,tex);CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());CHECK(cudaMemcpy(result.data(),output,result.size()*4,cudaMemcpyDeviceToHost));for(int i=w*h;i<w*h+16;i++)if(result[i]!=0xdeadbeef)return 1;char path[128];snprintf(path,sizeof(path),"reports/bilateral-filter-native-%d.bin",k);FILE* f=fopen(path,"wb");if(!f||fwrite(result.data(),4,result.size(),f)!=result.size())return 2;fclose(f);printf("case=%d %dx%d radius=%d range=%g native original kernel PASS; guards unchanged\n",k,w,h,r,ranges[k]);CHECK(cudaFree(output));CHECK(cudaDestroyTextureObject(tex));CHECK(cudaFreeArray(array));}return 0;}
