import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {compile} from '../src/compiler/compiler.js';import {executeCPU} from '../src/compiler/cpu-oracle.js';import {fwtPassFixture} from '../showcases/nvidia/fwt-pass-fixtures.js';
test('Buffer aliases capture offsets, chain and allow indexing back within the allocation',()=>{const c=compile('__global__ void k(int* out){int offset=2;int* p=out+offset;offset=4;int* q=p+1;p[0]=8;q[-1]+=3;}',{workgroupSize:[1,1,1]}),out=new Int32Array(6);executeCPU(c,{out},{},[1]);assert.deepEqual([...out],[0,0,11,0,0,0]);assert.equal(c.metadata.bindings[0].readOnly,false);});
test('Alias analysis preserves lexical scopes and read-only source bindings',()=>{const c=compile('__global__ void k(int* input,int* out){int* p=input;{int* p=out;p[0]=7;}out[1]=p[0];}',{workgroupSize:[1,1,1]}),input=new Int32Array([9]),out=new Int32Array(2);executeCPU(c,{input,out},{},[1]);assert.deepEqual([...out],[7,9]);assert.equal(c.metadata.bindings[0].readOnly,true);assert.equal(c.metadata.bindings[1].readOnly,false);});
test('Atomics through an alias mark the original binding atomic',()=>{const c=compile('__global__ void k(unsigned int* out){unsigned int* p=out+1;atomicAdd(&p[0],1u);}',{workgroupSize:[32,1,1]}),out=new Uint32Array(2);executeCPU(c,{out},{},[1]);assert.deepEqual([...out],[0,32]);assert.equal(c.metadata.bindings[0].atomic,true);});
test('Aliases reject const removal, writes through const and unsupported pointer operations',()=>{
 for(const source of ['__global__ void k(const float* out){float* p=out;}','__global__ void k(float* out){const float* p=out;p[0]=1.0f;}','__global__ void k(float* out){int* p=out+1;}','__global__ void k(float* out){float* p=out+1.5f;}','__global__ void k(float* out){float* p=out;p++;}','__global__ void k(float* out,float* other){float* p=out;p=other;}','__global__ void k(float* out){float s[4];float* p=s;}'])assert.throws(()=>compile(source));
});
test('Original FWT global pass agrees with independent butterfly equations',()=>{const c=compile(readFileSync('showcases/nvidia/kernels/29.cu','utf8'),{workgroupSize:[32,1,1]}),f=fwtPassFixture(2,3,32,16,16);executeCPU(c,f.buffers,f.scalars,f.groups);assert.deepEqual(f.buffers.d_Output,f.expected);});

test('Chained storage aliases retain write and atomic binding analysis',()=>{const a=compile('__global__ void k(uint*out){uint* p=out+2-1;atomicAdd(&p[0],1u);}',{workgroupSize:[4,1,1]}),out=new Uint32Array(3);executeCPU(a,{out},{},[1]);assert.deepEqual([...out],[0,4,0]);assert.equal(a.metadata.bindings[0].atomic,true);assert.equal(a.metadata.bindings[0].readOnly,false);});

test('Explicit buffer aliases retain independent mutable pointer offsets',()=>{const a=compile('__global__ void k(uint*a,uint*b){a+=1;b+=2;a[0]=b[0]+1;b[0]=a[0]+2;}',{workgroupSize:[1,1,1],bufferAliases:{b:'a'}}),data=Uint32Array.of(1,2,3,4);executeCPU(a,{a:data},{},[1]);assert.deepEqual([...data],[1,4,6,4]);assert.throws(()=>executeCPU(a,{a:data,b:new Uint32Array(4)},{},[1]),/alias/);});
test('Buffer alias declarations reject unknown parameters, mismatched types, self references and chains',()=>{const source='__global__ void k(uint*a,uint*b,float*c,uint n){a[0]=b[0];}';for(const bufferAliases of [{a:'a'},{x:'a'},{b:'c'},{n:'a'},{a:'b',b:'a'},[]])assert.throws(()=>compile(source,{bufferAliases}),/alias|Aliases/);});
