// MIT validation host. Included NVIDIA kernels retain the BSD notice.
#include <cuda_runtime.h>
#include <helper_image.h>
#include <vector>
#include <algorithm>
#include <cmath>
#include <cstdio>
#include "convolution-texture-kernel.cuh"
#define CHECK(x) do{auto e=(x);if(e!=cudaSuccess){printf("CUDA ERROR %s\n",cudaGetErrorString(e));return 2;}}while(0)
int main(){const int widths[]={128,35,8,512},heights[]={64,19,5,512},binomial[]={1,16,120,560,1820,4368,8008,11440,12870,11440,8008,4368,1820,560,120,16,1};
for(int scenario=0;scenario<4;scenario++){int w=widths[scenario],h=heights[scenario],count=w*h;std::vector<float> input(count),expected(count),next(count),actual(count+16,-12345);for(int i=0;i<count;i++)input[i]=float((i*37+(i/w)*13)%256)/255;if(scenario==3){float* pgm=nullptr;unsigned pw,ph;if(!sdkLoadPGM("showcases/texture2d/teapot512.pgm",&pgm,&pw,&ph)||pw!=w||ph!=h)return 2;std::copy(pgm,pgm+count,input.begin());free(pgm);}float coefficients[17];for(int i=0;i<17;i++)coefficients[i]=scenario==3?float(binomial[i])/65536:scenario==2?(i==8?1.f:0.f):float(i+1)/256;CHECK(cudaMemcpyToSymbol(c_Kernel,coefficients,sizeof(coefficients)));cudaArray_t array;auto channel=cudaCreateChannelDesc<float>();CHECK(cudaMallocArray(&array,&channel,w,h));CHECK(cudaMemcpy2DToArray(array,0,0,input.data(),w*4,w*4,h,cudaMemcpyHostToDevice));cudaResourceDesc resource={};resource.resType=cudaResourceTypeArray;resource.res.array.array=array;cudaTextureDesc desc={};desc.normalizedCoords=false;desc.filterMode=cudaFilterModeLinear;desc.addressMode[0]=desc.addressMode[1]=cudaAddressModeWrap;desc.readMode=cudaReadModeElementType;cudaTextureObject_t texture;CHECK(cudaCreateTextureObject(&texture,&resource,&desc,nullptr));float* output;CHECK(cudaMalloc(&output,actual.size()*4));CHECK(cudaMemcpy(output,actual.data(),actual.size()*4,cudaMemcpyHostToDevice));expected=input;
for(int stage=0;stage<2;stage++){if(stage)convolutionColumnsKernel<<<dim3((w+15)/16,(h+11)/12),dim3(16,12)>>>(output,w,h,texture);else convolutionRowsKernel<<<dim3((w+15)/16,(h+11)/12),dim3(16,12)>>>(output,w,h,texture);CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());CHECK(cudaMemcpy(actual.data(),output,actual.size()*4,cudaMemcpyDeviceToHost));for(int y=0;y<h;y++)for(int x=0;x<w;x++){double sum=0;for(int k=-8;k<=8;k++){int sx=stage?x:std::max(0,std::min(w-1,x+k)),sy=stage?std::max(0,std::min(h-1,y+k)):y;sum+=double(expected[sy*w+sx])*coefficients[8-k];}next[y*w+x]=float(sum);}float maxError=0;for(int i=0;i<count+16;i++){if(i>=count){if(actual[i]!=-12345)return 1;continue;}float error=std::abs(actual[i]-next[i]);maxError=std::max(maxError,error);if(!std::isfinite(actual[i])||error>3e-5f){printf("FAIL scenario=%d stage=%d pixel=%d error=%g\n",scenario,stage,i,error);return 1;}}char path[128];snprintf(path,sizeof(path),"reports/convolution-texture-native-%d-%d.bin",scenario,stage);FILE* file=fopen(path,"wb");if(!file||fwrite(actual.data(),4,actual.size(),file)!=actual.size())return 2;fclose(file);printf("scenario=%d %dx%d %s PASS all pixels, clamped borders and guards; max independent error %g\n",scenario,w,h,stage?"columns":"rows",maxError);expected=next;if(!stage)CHECK(cudaMemcpy2DToArray(array,0,0,output,w*4,w*4,h,cudaMemcpyDeviceToDevice));}
CHECK(cudaFree(output));CHECK(cudaDestroyTextureObject(texture));CHECK(cudaFreeArray(array));}return 0;}
