// SPDX-License-Identifier: MIT
#include <cuda_runtime.h>
#include <cooperative_groups.h>
#include <vector>
#include <cstdio>
#include <cmath>
#include "dct-float-kernel.cuh"
#include <helper_image.h>
#define CHECK(x) do{auto e=(x);if(e!=cudaSuccess){printf("CUDA ERROR %s\n",cudaGetErrorString(e));return 2;}}while(0)
int main(){const int w=512,h=512,n=w*h;std::vector<float> input(n),output(n+16,-12345);unsigned char*rgb=nullptr;unsigned iw=0,ih=0;if(!sdkLoadPPMub("showcases/dct/teapot512.ppm",&rgb,&iw,&ih)||iw!=w||ih!=h)return 2;for(int i=0;i<n;i++){int r=rgb[i*3],g=rgb[i*3+1],b=rgb[i*3+2];input[i]=float((313524*r+615514*g+119537*b+524288)>>20)-128.f;}free(rgb);FILE*prepared=fopen("reports/dct-teapot-input.bin","wb");if(!prepared||fwrite(input.data(),4,n,prepared)!=n)return 2;fclose(prepared);cudaArray_t array;auto channel=cudaCreateChannelDesc<float>();CHECK(cudaMallocArray(&array,&channel,w,h));CHECK(cudaMemcpy2DToArray(array,0,0,input.data(),w*4,w*4,h,cudaMemcpyHostToDevice));cudaResourceDesc resource={};resource.resType=cudaResourceTypeArray;resource.res.array.array=array;cudaTextureDesc desc={};desc.filterMode=cudaFilterModePoint;desc.readMode=cudaReadModeElementType;desc.addressMode[0]=desc.addressMode[1]=cudaAddressModeClamp;cudaTextureObject_t tex;CHECK(cudaCreateTextureObject(&tex,&resource,&desc,nullptr));float*dst;CHECK(cudaMalloc(&dst,output.size()*4));CHECK(cudaMemcpy(dst,output.data(),output.size()*4,cudaMemcpyHostToDevice));dim3 grid(w/8,h/8),block(8,8);for(int pass=0;pass<3;pass++){if(pass==0)CUDAkernel1DCT<<<grid,block>>>(dst,w,0,0,tex);if(pass==1)CUDAkernelQuantizationFloat<<<grid,block>>>(dst,w);if(pass==2){CHECK(cudaMemcpy2DToArray(array,0,0,dst,w*4,w*4,h,cudaMemcpyDeviceToDevice));CUDAkernel1IDCT<<<grid,block>>>(dst,w,0,0,tex);}CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());CHECK(cudaMemcpy(output.data(),dst,output.size()*4,cudaMemcpyDeviceToHost));for(int i=0;i<n;i++)if(!std::isfinite(output[i]))return 3;for(int i=n;i<n+16;i++)if(output[i]!=-12345)return 3;char path[128];snprintf(path,sizeof(path),"reports/dct-teapot-native-%d.bin",pass);FILE*f=fopen(path,"wb");if(!f||fwrite(output.data(),4,output.size(),f)!=output.size())return 2;fclose(f);printf("PASS native DCT/quantize/IDCT stage %d, %d finite outputs and guards.\n",pass,n);}std::vector<float> display(n);for(int i=0;i<n;i++)display[i]=fminf(255.f,fmaxf(0.f,roundf(output[i]+128.f)))/255.f;FILE*image=fopen("reports/dct-teapot-display.bin","wb");if(!image||fwrite(display.data(),4,n,image)!=n)return 2;fclose(image);CHECK(cudaFree(dst));CHECK(cudaDestroyTextureObject(tex));CHECK(cudaFreeArray(array));}
