// SPDX-License-Identifier: MIT
#include <cuda_runtime.h>
#include <cooperative_groups.h>
#include <vector>
#include <cstdio>
#include <cmath>
#include "dct-float-kernel.cuh"
#include "dct-rounding.cu"
#define CHECK(x) do{auto e=(x);if(e!=cudaSuccess){printf("CUDA ERROR %s\n",cudaGetErrorString(e));return 2;}}while(0)
int main(){float probeInput[]={-.5f,.5f,-1.5f,1.5f,-.49f,.49f,8388609.f,-8388609.f,16777216.f,-16777216.f,2.25f,-2.25f},probeResult[16],*probeSrc,*probeDst;CHECK(cudaMalloc(&probeSrc,sizeof(probeInput)));CHECK(cudaMalloc(&probeDst,sizeof(probeResult)));CHECK(cudaMemcpy(probeSrc,probeInput,sizeof(probeInput),cudaMemcpyHostToDevice));roundingProbe<<<1,16>>>(probeSrc,probeDst);CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());CHECK(cudaMemcpy(probeResult,probeDst,sizeof(probeResult),cudaMemcpyDeviceToHost));FILE*probeFile=fopen("reports/dct-rounding-native.bin","wb");if(!probeFile||fwrite(probeResult,4,16,probeFile)!=16)return 2;fclose(probeFile);CHECK(cudaFree(probeSrc));CHECK(cudaFree(probeDst));const int w=32,h=24,n=w*h;std::vector<float> input(n),output(n+16,-12345);for(int i=0;i<n;i++)input[i]=float((i*37+(i/w)*13)%256)-128;cudaArray_t array;auto channel=cudaCreateChannelDesc<float>();CHECK(cudaMallocArray(&array,&channel,w,h));CHECK(cudaMemcpy2DToArray(array,0,0,input.data(),w*4,w*4,h,cudaMemcpyHostToDevice));cudaResourceDesc resource={};resource.resType=cudaResourceTypeArray;resource.res.array.array=array;cudaTextureDesc desc={};desc.filterMode=cudaFilterModePoint;desc.readMode=cudaReadModeElementType;desc.addressMode[0]=desc.addressMode[1]=cudaAddressModeClamp;cudaTextureObject_t tex;CHECK(cudaCreateTextureObject(&tex,&resource,&desc,nullptr));float*dst;CHECK(cudaMalloc(&dst,output.size()*4));CHECK(cudaMemcpy(dst,output.data(),output.size()*4,cudaMemcpyHostToDevice));dim3 grid(w/8,h/8),block(8,8);for(int pass=0;pass<3;pass++){if(pass==0)CUDAkernel1DCT<<<grid,block>>>(dst,w,0,0,tex);if(pass==1)CUDAkernelQuantizationFloat<<<grid,block>>>(dst,w);if(pass==2){CHECK(cudaMemcpy2DToArray(array,0,0,dst,w*4,w*4,h,cudaMemcpyDeviceToDevice));CUDAkernel1IDCT<<<grid,block>>>(dst,w,0,0,tex);}CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());CHECK(cudaMemcpy(output.data(),dst,output.size()*4,cudaMemcpyDeviceToHost));for(int i=0;i<n;i++)if(!std::isfinite(output[i]))return 3;for(int i=n;i<n+16;i++)if(output[i]!=-12345)return 3;char path[128];snprintf(path,sizeof(path),"reports/dct-float-native-%d.bin",pass);FILE*f=fopen(path,"wb");if(!f||fwrite(output.data(),4,output.size(),f)!=output.size())return 2;fclose(f);printf("PASS native DCT/quantize/IDCT stage %d, %d finite outputs and guards.\n",pass,n);}CHECK(cudaFree(dst));CHECK(cudaDestroyTextureObject(tex));CHECK(cudaFreeArray(array));}
