// SPDX-License-Identifier: MIT
#include <cuda_runtime.h>
#include <cooperative_groups.h>
#include <vector>
#include <cstdio>
#include "denoising-kernel.cuh"
extern "C" void LoadBMPFile(uchar4**,int*,int*,const char*);
#define CHECK(x) do{auto e=(x);if(e!=cudaSuccess){printf("CUDA ERROR %s\n",cudaGetErrorString(e));return 2;}}while(0)
int main(int argc,char**argv){int w=32,h=24;std::vector<uchar4> input;if(argc>1){uchar4* original=nullptr;LoadBMPFile(&original,&w,&h,"showcases/denoising/portrait_noise.bmp");input.assign(original,original+w*h);free(original);}else{input.resize(w*h);for(int i=0;i<w*h;i++)input[i]=make_uchar4((i*37)&255,(i*13+i/w*7)&255,(i*3+97)&255,0);}const int n=w*h;cudaArray_t array;auto channel=cudaCreateChannelDesc<uchar4>();CHECK(cudaMallocArray(&array,&channel,w,h));CHECK(cudaMemcpy2DToArray(array,0,0,input.data(),w*4,w*4,h,cudaMemcpyHostToDevice));cudaResourceDesc resource={};resource.resType=cudaResourceTypeArray;resource.res.array.array=array;cudaTextureDesc desc={};desc.filterMode=cudaFilterModeLinear;desc.readMode=cudaReadModeNormalizedFloat;desc.addressMode[0]=desc.addressMode[1]=cudaAddressModeWrap;cudaTextureObject_t tex;CHECK(cudaCreateTextureObject(&tex,&resource,&desc,nullptr));unsigned* dst;CHECK(cudaMalloc(&dst,(n+16)*4));dim3 grid(w/8,h/8),block(8,8);const char* names[]={"Copy","KNN","KNNdiag","NLM","NLMdiag","NLM2","NLM2diag"};
for(int k=0;k<7;k++){const float level=k<3?.32f:1.45f,noise=argc>1?1.f/(level*level):32.f;std::vector<unsigned> output(n+16,0xdeadbeef);CHECK(cudaMemcpy(dst,output.data(),output.size()*4,cudaMemcpyHostToDevice));switch(k){case 0:Copy<<<grid,block>>>(dst,w,h,tex);break;case 1:KNN<<<grid,block>>>(dst,w,h,noise,.2f,tex);break;case 2:KNNdiag<<<grid,block>>>(dst,w,h,noise,.2f,tex);break;case 3:NLM<<<grid,block>>>(dst,w,h,noise,.2f,tex);break;case 4:NLMdiag<<<grid,block>>>(dst,w,h,noise,.2f,tex);break;case 5:NLM2<<<grid,block>>>(dst,w,h,noise,.2f,tex);break;case 6:NLM2diag<<<grid,block>>>(dst,w,h,noise,.2f,tex);break;}CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());CHECK(cudaMemcpy(output.data(),dst,output.size()*4,cudaMemcpyDeviceToHost));for(int i=n;i<n+16;i++)if(output[i]!=0xdeadbeef)return 3;char path[128];snprintf(path,sizeof(path),"reports/denoising-%s-%s.bin",argc>1?"portrait":"native",names[k]);FILE*f=fopen(path,"wb");if(!f||fwrite(output.data(),4,output.size(),f)!=output.size())return 2;fclose(f);printf("PASS %s native launch %dx%d and guards.\n",names[k],w,h);}
CHECK(cudaFree(dst));CHECK(cudaDestroyTextureObject(tex));CHECK(cudaFreeArray(array));}
