// SPDX-License-Identifier: MIT
#include <cuda_runtime.h>
#include <helper_cuda.h>
#include <helper_functions.h>
#include <helper_math.h>
#include <vector>
#include "permutations.h"
#include "dxt-evaluate-kernels.cuh"
bool save(const char*p,const void*d,size_t bytes){FILE*f=fopen(p,"wb");if(!f)return false;bool ok=fwrite(d,1,bytes,f)==bytes;fclose(f);return ok;}
int main(){unsigned char*image=nullptr;unsigned width,height;if(!sdkLoadPPM4ub(".local/nvidia-audit/cpp/5_Domain_Specific/dxtc/data/teapot512_std.ppm",&image,&width,&height))return 2;uint permutations[1024];computePermutations(permutations);if(!save("reports/dxt-permutations.bin",permutations,sizeof(permutations)))return 2;uint*dp;float4*di,*de;uint4*do_;checkCudaErrors(cudaMalloc(&dp,sizeof(permutations)));checkCudaErrors(cudaMalloc(&di,16*sizeof(float4)));checkCudaErrors(cudaMalloc(&de,1024*sizeof(float4)));checkCudaErrors(cudaMalloc(&do_,1024*sizeof(uint4)));checkCudaErrors(cudaMemcpy(dp,permutations,sizeof(permutations),cudaMemcpyHostToDevice));int blocks[][2]={{21,98},{64,64},{100,100},{0,0}};for(int c=0;c<4;c++){float4 colors[16],errors[1024];uint4 endpoints[1024];for(int i=0;i<16;i++){int x=blocks[c][0]*4+i%4,y=blocks[c][1]*4+i/4,offset=(y*width+x)*4;colors[i]=make_float4(image[offset]/255.f,image[offset+1]/255.f,image[offset+2]/255.f,1.f);}checkCudaErrors(cudaMemcpy(di,colors,sizeof(colors),cudaMemcpyHostToDevice));dxtEvaluate<<<16,64>>>(di,dp,de,do_,1024);checkCudaErrors(cudaMemcpy(errors,de,sizeof(errors),cudaMemcpyDeviceToHost));checkCudaErrors(cudaMemcpy(endpoints,do_,sizeof(endpoints),cudaMemcpyDeviceToHost));char path[150];snprintf(path,sizeof(path),"reports/dxt-evaluate-%d-input.bin",c);if(!save(path,colors,sizeof(colors)))return 2;snprintf(path,sizeof(path),"reports/dxt-evaluate-%d-errors.bin",c);if(!save(path,errors,sizeof(errors)))return 2;snprintf(path,sizeof(path),"reports/dxt-evaluate-%d-endpoints.bin",c);if(!save(path,endpoints,sizeof(endpoints)))return 2;printf("Captured original 3/4-colour endpoint fitting: 1024 permutations at block (%d,%d).\n",blocks[c][0],blocks[c][1]);}free(image);for(void*p:{(void*)dp,(void*)di,(void*)de,(void*)do_})checkCudaErrors(cudaFree(p));}
