export async function checkFluids(runtime){
 const load=async name=>new Float32Array(await(await fetch('/reports/'+name+'.bin')).arrayBuffer()),input=await load('fluids-velocity-input');
 const source=await(await fetch('/tests/fluids-advectVelocity_k.cuh')).text(),advection=await runtime.kernel(source,{entry:'advectVelocity_k',workgroupSize:[16,4,1]}),projection=await runtime.kernel(await(await fetch('/tests/fluids-diffuseProject_k.cuh')).text(),{entry:'diffuseProject_k',workgroupSize:[16,4,1]});
 const v=runtime.createBuffer(input),x=runtime.createBuffer(new Float32Array(24*13+16).fill(-77)),y=runtime.createBuffer(new Float32Array(24*13+16).fill(-77)),texture=runtime.createTexture2D(input,{width:19,height:13,format:'rg32float',filter:'linear',addressMode:'clamp-to-edge',normalizedCoords:false}),comparisons=[];
 const slope=[0,1].map(c=>{let dx=0,dy=0;for(let y=0;y<13;y++)for(let x=0;x<19;x++){const value=input[(y*19+x)*2+c];if(x<18)dx=Math.max(dx,Math.abs(value-input[(y*19+x+1)*2+c]));if(y<12)dy=Math.max(dy,Math.abs(value-input[((y+1)*19+x)*2+c]));}return (dx+dy)/256+1e-6;});
 const bilinear=(x,y,c)=>{const ix=Math.floor(x-.5),iy=Math.floor(y-.5),a=x-.5-ix,b=y-.5-iy,get=(px,py)=>input[(Math.max(0,Math.min(12,py))*19+Math.max(0,Math.min(18,px)))*2+c];return (get(ix,iy)*(1-a)+get(ix+1,iy)*a)*(1-b)+(get(ix,iy+1)*(1-a)+get(ix+1,iy+1)*a)*b;};
 const compare=async(resource,name)=>{const actual=await runtime.read(resource),expected=await load(name);if(actual.length!==expected.length)throw Error('Wrong fluid native capture');let maxError=0;for(let i=0;i<actual.length;i++){if(!Number.isFinite(actual[i]))throw Error('Nonfinite fluid output');maxError=Math.max(maxError,Math.abs(actual[i]-expected[i]));if(expected[i]===-77&&actual[i]!==-77)throw Error('Fluid padding overwritten');}const tolerance=name.includes('advect-1-')?2*slope[Number(name.split('-').at(-2))]:1e-6;if(maxError>tolerance)throw Error('Fluid native mismatch '+name+': '+maxError);comparisons.push({name,components:actual.length,maxError,tolerance,exact:maxError===0});};
 const cx=runtime.createBuffer(input),cy=runtime.createBuffer(input);
 try{
  for(let mode=0;mode<3;mode++){runtime.batch().dispatch(advection.bind({v,vx:x,vy:y,texObject:texture},{dx:19,pdx:24,dy:13,dt:[0,.09,1][mode],lb:3}),[2,2,1]).submit();await compare(x,'fluids-advect-'+mode+'-0-native');await compare(y,'fluids-advect-'+mode+'-1-native');}
  runtime.batch().dispatch(projection.bind({vx:cx,vy:cy},{dx:19,dy:13,dt:.09,visc:.0025,lb:3}),[2,2,1]).submit();await compare(cx,'fluids-project-0-native');await compare(cy,'fluids-project-1-native');
  const probe=await runtime.kernel('__global__ void sampleCoordinates(cudaTextureObject_t texture,const float4*trace,float2*output,unsigned count){unsigned i=blockIdx.x*blockDim.x+threadIdx.x;if(i<count){float4 p=trace[i];output[i]=tex2D<float2>(texture,p.z,p.w);}}',{workgroupSize:[128,1,1]});
  for(let mode=0;mode<3;mode++){
   const captured=await load('fluids-trace-'+mode),coordinates=runtime.createBuffer(captured),output=runtime.createBuffer(19*13*8);
   try{runtime.batch().dispatch(advection.bind({v,vx:x,vy:y,texObject:texture},{dx:19,pdx:24,dy:13,dt:[0,.09,1][mode],lb:3}),[2,2,1]).submit();const components=[await runtime.read(x),await runtime.read(y)];runtime.batch().dispatch(probe.bind({texture,trace:coordinates,output},{count:19*13}),[2,1,1]).submit();const sampled=await runtime.read(output);let maxError=0,nativeVsBilinear=0,webgpuVsBilinear=0;for(let i=0;i<19*13;i++)for(let c=0;c<2;c++){maxError=Math.max(maxError,Math.abs(sampled[i*2+c]-captured[i*4+c]));if(Math.abs(sampled[i*2+c]-components[c][Math.floor(i/19)*24+i%19])>1e-6)throw Error('Backtrace differs from CUDA captured coordinates');const reference=bilinear(captured[i*4+2],captured[i*4+3],c),nativeError=Math.abs(captured[i*4+c]-reference),webgpuError=Math.abs(sampled[i*2+c]-reference);if(!Number.isFinite(sampled[i*2+c])||nativeError>slope[c]||webgpuError>slope[c])throw Error('Float2 interpolation exceeds gradient-derived filtering bound');nativeVsBilinear=Math.max(nativeVsBilinear,nativeError);webgpuVsBilinear=Math.max(webgpuVsBilinear,webgpuError);}comparisons.push({name:'isolated sampler '+mode,maxError,nativeVsBilinear,webgpuVsBilinear,advectionMatchesCapturedCoordinates:true});}finally{runtime.destroyBuffer(coordinates);runtime.destroyBuffer(output);}
  }
  return {comparisons,filteringBoundPerChannel:slope,filteringNote:'Each backend checked against ideal bilinear interpolation using (maximum horizontal slope + maximum vertical slope)/256 + 1e-6. Cross-backend tolerance is twice that bound; it is not an exact match claim.',originalKernelBodies:true,paddedRows:true,partialWorkgroups:true};
 }finally{[v,x,y,cx,cy].forEach(b=>runtime.destroyBuffer(b));runtime.destroyTexture(texture);}
}
