import test from 'node:test';import assert from 'node:assert/strict';import {compile} from '../src/compiler/compiler.js';import {executeCPU} from '../src/compiler/cpu-oracle.js';
function run(source){const c=compile(source,{workgroupSize:[1,1,1]}),out=new Float32Array(8);executeCPU(c,{out},{},[1]);return {c,out};}
test('Helper deduction follows scalar argument types and nested helper return types',()=>{const {c,out}=run('template<class T> __device__ T square(T x){return x*x;} template<class T> __device__ T nested(T x){return square(x)+x;} __global__ void k(float* out){out[0]=nested(1.5f);out[1]=nested(3);out[2]=square(nested(2.0f));out[3]=square<float>(2.0f);}');assert.deepEqual([...out.slice(0,4)],[3.75,12,36,4]);assert.equal(c.ast.functions.filter(f=>f.qualifier==='__device__').length,4);});
test('Deduced references preserve mutations and vector values preserve their type',()=>{const {out}=run('template<class T> __device__ void swap(T& a,T& b){T t=a;a=b;b=t;} template<class T> __device__ T id(T x){return x;} __global__ void k(float* out){float a=2.0f;float b=7.0f;swap(a,b);float4 v=id(make_float4(1.0f,2.0f,3.0f,4.0f));out[0]=a;out[1]=b;out[2]=v.z;}');assert.deepEqual([...out.slice(0,3)],[7,2,3]);});
test('Conflicting deductions fail instead of converting mismatched argument types',()=>{assert.throws(()=>compile('template<class T> __device__ T add(T a,T b){return a+b;} __global__ void k(){add(1,2.0f);}'),/Conflicting deduced/);assert.throws(()=>compile('template<class T> __device__ T add(T a,T b){return a+b;} __global__ void k(){add(1,2u);}'),/Conflicting deduced/);});
test('Deduction rejects missing type evidence, pointer arguments and implicit integer templates',()=>{for(const source of ['template<class T> __device__ T f(){return (T)1;} __global__ void k(){f();}','template<class T> __device__ void f(T* x){} __global__ void k(float* x){f(x);}','template<int N> __device__ int f(int x){return x+N;} __global__ void k(){f(1);}'])assert.throws(()=>compile(source),/deduce|explicit template/);});
test('Recursive deduced helper calls are rejected before WGSL or CPU execution',()=>{assert.throws(()=>compile('template<class T> __device__ T f(T x){return f(x);} __global__ void k(){f(1.0f);}'),/Recursive helper/);assert.throws(()=>compile('template<class T> __device__ T f(T x){return f((int)x);} __global__ void k(){f(1.0f);}'),/Recursive helper/);});
test('Non-deduced trait parameters resolve using a direct template parameter',()=>{const {out}=run('template<class U> struct V{typedef float4 Type;}; template<class T> __device__ float f(typename V<T>::Type v,T scale){return v.x*scale;} __global__ void k(float* out){out[0]=f(make_float4(3.0f,0.0f,0.0f,0.0f),2.0f);}');assert.equal(out[0],6);});
test('Calls from an existing non-template helper can instantiate new helper templates',()=>{const {out}=run('template<class T> __device__ T twice(T x){return x+x;} __device__ float wrapper(float x){return twice(x);} __global__ void k(float* out){out[0]=wrapper(4.0f);}');assert.equal(out[0],8);});
