// SPDX-License-Identifier: MIT
#include <cuda_runtime.h>
#include <helper_math.h>
#include <cstdio>
#include <vector>
#define _DEFINES_H_
#define SAMPLE_VOLUME 1
#define USE_SHARED 1
#define NTHREADS 32
#define SKIP_EMPTY_VOXELS 1
typedef unsigned char uchar;
#include "marching-cubes-kernel.cuh"
#include "marching-cubes-tables.cuh"
#define CHECK(x) do{auto e=(x);if(e!=cudaSuccess){printf("CUDA ERROR %s\n",cudaGetErrorString(e));return 2;}}while(0)
int main(){const unsigned int count=32768;std::vector<uchar> bytes(count);FILE* raw=fopen("tests/marching-bucky.raw","rb");if(!raw||fread(bytes.data(),1,count,raw)!=count)return 2;fclose(raw);uchar* volume;CHECK(cudaMalloc(&volume,count));CHECK(cudaMemcpy(volume,bytes.data(),count,cudaMemcpyHostToDevice));cudaResourceDesc vr={};vr.resType=cudaResourceTypeLinear;vr.res.linear.devPtr=volume;vr.res.linear.sizeInBytes=count;vr.res.linear.desc=cudaCreateChannelDesc<uchar>();cudaTextureDesc vd={};vd.readMode=cudaReadModeNormalizedFloat;cudaTextureObject_t volumeTex;CHECK(cudaCreateTextureObject(&volumeTex,&vr,&vd,nullptr));unsigned int *table,*tri,*verts,*occupied,*scan,*occupiedScan,*compacted;CHECK(cudaMalloc(&table,256*4));CHECK(cudaMalloc(&tri,4096*4));CHECK(cudaMalloc(&verts,count*4));CHECK(cudaMalloc(&occupied,count*4));CHECK(cudaMalloc(&scan,count*4));CHECK(cudaMalloc(&occupiedScan,count*4));CHECK(cudaMalloc(&compacted,count*4));CHECK(cudaMemcpy(table,numVertsTable,256*4,cudaMemcpyHostToDevice));CHECK(cudaMemcpy(tri,triTable,4096*4,cudaMemcpyHostToDevice));cudaTextureObject_t textures[2];for(int i=0;i<2;i++){cudaResourceDesc r={};r.resType=cudaResourceTypeLinear;r.res.linear.devPtr=i?tri:table;r.res.linear.sizeInBytes=i?4096*4:256*4;r.res.linear.desc=cudaCreateChannelDesc<unsigned int>();cudaTextureDesc d={};d.readMode=cudaReadModeElementType;CHECK(cudaCreateTextureObject(&textures[i],&r,&d,nullptr));}
 float isos[]={.2f,.5f,.8f};for(int scenario=0;scenario<3;scenario++){const float iso=isos[scenario];classifyVoxel<<<256,128>>>(verts,occupied,volume,make_uint3(32,32,32),make_uint3(0,5,10),make_uint3(31,31,31),count,make_float3(.0625f,.0625f,.0625f),iso,textures[0],volumeTex);CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());std::vector<unsigned int> v(count),o(count),sc(count),os(count),compact(count);CHECK(cudaMemcpy(v.data(),verts,count*4,cudaMemcpyDeviceToHost));CHECK(cudaMemcpy(o.data(),occupied,count*4,cudaMemcpyDeviceToHost));unsigned int active=0,total=0;for(unsigned int i=0;i<count;i++){sc[i]=total;os[i]=active;total+=v[i];active+=o[i];}CHECK(cudaMemcpy(scan,sc.data(),count*4,cudaMemcpyHostToDevice));CHECK(cudaMemcpy(occupiedScan,os.data(),count*4,cudaMemcpyHostToDevice));compactVoxels<<<256,128>>>(compacted,occupied,occupiedScan,count);CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());CHECK(cudaMemcpy(compact.data(),compacted,count*4,cudaMemcpyDeviceToHost));for(int i=0;i<2;i++){char path[128];snprintf(path,sizeof(path),"reports/marching-volume-native-%d-%s.bin",scenario,i?"compacted":"scan");FILE* file=fopen(path,"wb");if(!file)return 2;fwrite(i?compact.data():sc.data(),4,i?active:count,file);fclose(file);}
 float4 *pos,*norm;CHECK(cudaMalloc(&pos,(total+3)*16));CHECK(cudaMalloc(&norm,(total+3)*16));CHECK(cudaMemset(pos,0,(total+3)*16));CHECK(cudaMemset(norm,0,(total+3)*16));generateTriangles2<<<(active+31)/32,32>>>(pos,norm,compacted,scan,volume,make_uint3(32,32,32),make_uint3(0,5,10),make_uint3(31,31,31),make_float3(.0625f,.0625f,.0625f),iso,active,total+3,textures[1],textures[0],volumeTex);CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());std::vector<float4> output(total);for(int i=0;i<2;i++){CHECK(cudaMemcpy(output.data(),i?norm:pos,total*16,cudaMemcpyDeviceToHost));char path[128];snprintf(path,sizeof(path),"reports/marching-volume-native-%d-%s.bin",scenario,i?"normals":"positions");FILE* f=fopen(path,"wb");if(!f)return 2;fwrite(output.data(),16,total,f);fclose(f);}CHECK(cudaFree(pos));CHECK(cudaFree(norm));printf("Bucky iso=%.9g active=%u vertices=%u shared generateTriangles2; native host scans prepare fixture.\n",iso,active,total);}CHECK(cudaFree(volume));CHECK(cudaDestroyTextureObject(volumeTex));for(auto p:{table,tri,verts,occupied,scan,occupiedScan,compacted})CHECK(cudaFree(p));for(auto t:textures)CHECK(cudaDestroyTextureObject(t));return 0;}
