// SPDX-License-Identifier: MIT
#include <cuda_runtime.h>
#include <helper_math.h>
#include <cstdio>
#include <vector>
#include "marching-cubes-kernel.cuh"
#include "marching-cubes-tables.cuh"
#define CHECK(x) do{auto e=(x);if(e!=cudaSuccess){printf("CUDA ERROR %s\n",cudaGetErrorString(e));return 2;}}while(0)
int main(){const unsigned int count=32768;std::vector<unsigned char> data(count);FILE* raw=fopen(".local/nvidia-audit/cpp/5_Domain_Specific/marchingCubes/data/Bucky.raw","rb");if(!raw||fread(data.data(),1,count,raw)!=count)return 2;fclose(raw);unsigned char* volume;unsigned int *table,*verts,*occupied;CHECK(cudaMalloc(&volume,count));CHECK(cudaMalloc(&table,256*4));CHECK(cudaMalloc(&verts,count*4));CHECK(cudaMalloc(&occupied,count*4));CHECK(cudaMemcpy(volume,data.data(),count,cudaMemcpyHostToDevice));CHECK(cudaMemcpy(table,numVertsTable,256*4,cudaMemcpyHostToDevice));cudaTextureObject_t textures[2];for(int i=0;i<2;i++){cudaResourceDesc r={};r.resType=cudaResourceTypeLinear;r.res.linear.devPtr=i?(void*)table:(void*)volume;r.res.linear.sizeInBytes=i?256*4:count;r.res.linear.desc=i?cudaCreateChannelDesc<unsigned int>():cudaCreateChannelDesc<unsigned char>();cudaTextureDesc d={};d.readMode=i?cudaReadModeElementType:cudaReadModeNormalizedFloat;CHECK(cudaCreateTextureObject(&textures[i],&r,&d,nullptr));}
 std::vector<unsigned int> v(count),o(count);float iso[]={.2f,.5f,.8f};for(int scenario=0;scenario<3;scenario++){classifyVoxel<<<dim3(16,16,1),128>>>(verts,occupied,volume,make_uint3(32,32,32),make_uint3(0,5,10),make_uint3(31,31,31),count,make_float3(.0625f,.0625f,.0625f),iso[scenario],textures[1],textures[0]);CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());CHECK(cudaMemcpy(v.data(),verts,count*4,cudaMemcpyDeviceToHost));CHECK(cudaMemcpy(o.data(),occupied,count*4,cudaMemcpyDeviceToHost));unsigned int active=0,total=0;for(unsigned int i=0;i<count;i++){active+=o[i];total+=v[i];}for(int i=0;i<2;i++){char path[128];snprintf(path,sizeof(path),"reports/marching-classify-native-%d-%s.bin",scenario,i?"occupied":"vertices");FILE* f=fopen(path,"wb");if(!f)return 2;fwrite(i?o.data():v.data(),4,count,f);fclose(f);}printf("iso=%.9g voxels=%u active=%u vertices=%u\n",iso[scenario],count,active,total);}
 for(auto t:textures)CHECK(cudaDestroyTextureObject(t));CHECK(cudaFree(volume));CHECK(cudaFree(table));CHECK(cudaFree(verts));CHECK(cudaFree(occupied));return 0;}
