// SPDX-License-Identifier: MIT
#include <cuda_runtime.h>
#include <helper_math.h>
#include <cstdio>
#include <vector>
#define _DEFINES_H_
#define SAMPLE_VOLUME 0
#define USE_SHARED 1
#define NTHREADS 32
#define SKIP_EMPTY_VOXELS 1
typedef unsigned char uchar;
#include "marching-cubes-kernel.cuh"
#include "marching-cubes-tables.cuh"
#define CHECK(x) do{auto e=(x);if(e!=cudaSuccess){printf("CUDA ERROR %s\n",cudaGetErrorString(e));return 2;}}while(0)
int main(){const unsigned int count=4096;unsigned int *table,*tri,*verts,*occupied,*scan,*occupiedScan,*compacted;CHECK(cudaMalloc(&table,256*4));CHECK(cudaMalloc(&tri,4096*4));CHECK(cudaMalloc(&verts,count*4));CHECK(cudaMalloc(&occupied,count*4));CHECK(cudaMalloc(&scan,count*4));CHECK(cudaMalloc(&occupiedScan,count*4));CHECK(cudaMalloc(&compacted,count*4));CHECK(cudaMemcpy(table,numVertsTable,256*4,cudaMemcpyHostToDevice));CHECK(cudaMemcpy(tri,triTable,4096*4,cudaMemcpyHostToDevice));cudaTextureObject_t textures[2];for(int i=0;i<2;i++){cudaResourceDesc r={};r.resType=cudaResourceTypeLinear;r.res.linear.devPtr=i?tri:table;r.res.linear.sizeInBytes=i?4096*4:256*4;r.res.linear.desc=cudaCreateChannelDesc<unsigned int>();cudaTextureDesc d={};d.readMode=cudaReadModeElementType;CHECK(cudaCreateTextureObject(&textures[i],&r,&d,nullptr));}
 classifyVoxel<<<32,128>>>(verts,occupied,nullptr,make_uint3(16,16,16),make_uint3(0,4,8),make_uint3(15,15,15),count,make_float3(.125f,.125f,.125f),.5f,textures[0],0);CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());std::vector<unsigned int> v(count),o(count),sc(count),os(count),compact(count);CHECK(cudaMemcpy(v.data(),verts,count*4,cudaMemcpyDeviceToHost));CHECK(cudaMemcpy(o.data(),occupied,count*4,cudaMemcpyDeviceToHost));unsigned int active=0,total=0;for(unsigned int i=0;i<count;i++){sc[i]=total;os[i]=active;total+=v[i];active+=o[i];}CHECK(cudaMemcpy(scan,sc.data(),count*4,cudaMemcpyHostToDevice));CHECK(cudaMemcpy(occupiedScan,os.data(),count*4,cudaMemcpyHostToDevice));compactVoxels<<<32,128>>>(compacted,occupied,occupiedScan,count);CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());CHECK(cudaMemcpy(compact.data(),compacted,count*4,cudaMemcpyDeviceToHost));for(int i=0;i<2;i++){FILE* file=fopen(i?"reports/marching-triangles-native-compacted.bin":"reports/marching-triangles-native-scan.bin","wb");if(!file)return 2;fwrite(i?compact.data():sc.data(),4,i?active:count,file);fclose(file);}
 float4 *pos,*norm;CHECK(cudaMalloc(&pos,total*16));CHECK(cudaMalloc(&norm,total*16));CHECK(cudaMemset(pos,0,total*16));CHECK(cudaMemset(norm,0,total*16));generateTriangles<<<(active+31)/32,32>>>(pos,norm,compacted,scan,make_uint3(16,16,16),make_uint3(0,4,8),make_uint3(15,15,15),make_float3(.125f,.125f,.125f),.5f,active,total,textures[1],textures[0]);CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());std::vector<float4> output(total);for(int i=0;i<2;i++){CHECK(cudaMemcpy(output.data(),i?norm:pos,total*16,cudaMemcpyDeviceToHost));FILE* f=fopen(i?"reports/marching-triangles-native-normals.bin":"reports/marching-triangles-native-positions.bin","wb");if(!f)return 2;fwrite(output.data(),16,total,f);fclose(f);}FILE* json=fopen("reports/marching-triangles-native.json","w");if(!json)return 2;fprintf(json,"{\"activeVoxels\":%u,\"maxVerts\":%u,\"gridSize\":16,\"isoValue\":0.5}\n",active,total);fclose(json);CHECK(cudaFree(pos));CHECK(cudaFree(norm));for(auto p:{table,tri,verts,occupied,scan,occupiedScan,compacted})CHECK(cudaFree(p));for(auto t:textures)CHECK(cudaDestroyTextureObject(t));printf("Original implicit field: active=%u vertices=%u; shared generateTriangles captured; CPU scans are fixture setup only.\n",active,total);return 0;}
