import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {compile} from '../src/compiler/compiler.js';import {executeCPU} from '../src/compiler/cpu-oracle.js';import {kernelSource} from '../src/sandbox/import.js';
const run=(source,entry)=>{const c=compile(source,{entry,workgroupSize:[1]}),out=new Float32Array(8);executeCPU(c,{out},{},[1]);return {c,out};};
test('Multiple helper types preserve argument order, conversion and full specialization',()=>{const {c,out}=run('template<class A,typename B> __device__ B f(A x){return (B)x+(B)1;} template<> __device__ float f<int, float>(int x){return (float)(x*10);} template<class X,class Y> __device__ float g(X x,Y y){return f<Y,X>(y)+f<X,Y>(x);} __global__ void k(float* out){out[0]=g<float,int>(2.5f,-3);out[1]=f<float,int>(2.5f);out[2]=f<int,float>(-3);}');assert.deepEqual([...out.slice(0,3)],[-27,3,-30]);assert.ok(c.ast.functions.every(f=>!f.result.startsWith('template:')));});
test('Four helper types substitute locals, casts, references, vectors and trait members',()=>{const {out}=run('template<class T> struct trait{typedef T Value;}; template<class A,class B,class C,class D> __device__ D f(A a,B b,C c,D& d){typename trait<B>::Value x=b;typename trait<A>::Value y=a;d=(D)y+(D)x+(D)c;return d;} template<class X,class Y> __device__ X first(X x,Y y){return x;} __global__ void k(float* out){float d=0.0f;out[0]=f<int,float,uint,float>(-2,2.5f,7u,d);out[1]=d;float4 v=first<float4,int>(make_float4(1.0f,2.0f,3.0f,4.0f),0);out[2]=v.w;}');assert.deepEqual([...out.slice(0,3)],[7.5,7.5,4]);});
test('Single kernel type parameters forward into several helper argument positions',()=>{const {out}=run('template<class A,class B> __device__ B f(A x){return (B)x;}template<class T> __global__ void k(float* out){out[0]=f<T,int>((T)3.5f);out[1]=f<float,T>(2.5f);}','k<float>');assert.deepEqual([...out.slice(0,2)],[3,2.5]);});
test('Texture helper type lists propagate sampling metadata through nested calls',()=>{const source=fs.readFileSync(new URL('multiple-helper-types.cu',import.meta.url),'utf8'),c=compile(kernelSource('#include <cuda_runtime.h>\n'+source).source,{workgroupSize:[1]});assert.equal(c.metadata.textures[0].format,'r32float');assert.match(c.wgsl,/textureSampleLevel/);assert.doesNotMatch(c.wgsl,/template:/);});
test('Unsupported template lists fail without silently dropping arguments',()=>{const helper='template<class A,class B> __device__ B f(A x){return (B)x;}';for(const args of ['float','float,int,uint','float,','float,3','float,void','float,cudaTextureObject_t'])assert.throws(()=>compile(helper+'__global__ void k(){f<'+args+'>(1.0f);}'),/Template|template/);assert.throws(()=>compile(helper+'__global__ void k(){f(1.0f);}'),/explicit template/);for(const decl of ['template<class A,class A>','template<class A,int N>','template<int N,class A>','template<class A,class B,class C,class D,class E>'])assert.throws(()=>compile(decl+' __device__ float f(){return 1.0f;}__global__ void k(){}'),/template|Template|four/);assert.throws(()=>compile('template<class A,class B> __global__ void k(){}'),/device helpers only/);assert.throws(()=>compile('template<class A,class B> struct trait{typedef A Value;};__global__ void k(){}'),/one template/);});
test('Multiple-type specializations reject recursion, shadowing, duplicates and signature mismatches',()=>{for(const source of [
 'template<class A,class B> __device__ A f(A x){return f<A,B>(x);}__global__ void k(){f<float,int>(1.0f);}',
 'template<class A,class B> __device__ A f(A B){return B;}__global__ void k(){f<float,int>(1.0f);}',
 'template<class A,class B> __device__ A f(A x){B B=(B)x;return x;}__global__ void k(){f<float,int>(1.0f);}',
 'template<class A,class B> __device__ B f(A x){return (B)x;}template<> __device__ int f<float,int>(int x){return x;}__global__ void k(){f<float,int>(1.0f);}',
 'template<class A,class B> __device__ B f(A x){return (B)x;}template<> __device__ int f<float, int>(float x){return (int)x;}template<> __device__ int f<float,int>(float x){return (int)x;}__global__ void k(){f<float,int>(1.0f);}'
 ])assert.throws(()=>compile(source),/Recursive|shadowing|signature|Duplicate/);});
