export async function checkOcean(runtime){
 if(runtime.describe().vendor!=='nvidia')throw Error('NVIDIA hardware required');
 const source=await(await fetch('/tests/ocean-kernel.cuh')).text(),h0=runtime.createBuffer(new Float32Array(await(await fetch('/reports/ocean-h0.bin')).arrayBuffer())),ht=runtime.createBuffer(256*256*8),height=runtime.createBuffer(256*256*4),slope=runtime.createBuffer(256*256*8),results=[];
 try{const spectrum=await runtime.kernel(source,{entry:'generateSpectrumKernel',workgroupSize:[8,8,1]}),update=await runtime.kernel(source,{entry:'updateHeightmapKernel',workgroupSize:[8,8,1]}),gradient=await runtime.kernel(source,{entry:'calculateSlopeKernel',workgroupSize:[8,8,1]});
 const check=async(c,stage,buffer)=>{const actual=await runtime.read(buffer),native=new Float32Array(await(await fetch('/reports/ocean-native-'+c+'-'+stage+'.bin')).arrayBuffer());if(actual.length!==native.length)throw Error('Capture size mismatch');let maxError=0,maxMagnitude=0,sumSquared=0;for(let i=0;i<actual.length;i++){if(!Number.isFinite(actual[i])||!Number.isFinite(native[i]))throw Error('Nonfinite ocean output');const e=Math.abs(actual[i]-native[i]);maxError=Math.max(maxError,e);maxMagnitude=Math.max(maxMagnitude,Math.abs(native[i]));sumSquared+=e*e;}results.push({case:c,stage,components:actual.length,maxError,maxMagnitude,rmsError:Math.sqrt(sumSquared/actual.length)});};
 for(const [c,t]of [0,1.25,7.5].entries()){runtime.batch().dispatch(spectrum.bind({h0,ht},{in_width:260,out_width:256,out_height:256,t,patchSize:100}),[32,32,1]).submit();await check(c,'spectrum',ht);await runtime.inverseFFT2D(ht,ht,{width:256,height:256});await check(c,'spatial',ht);runtime.batch().dispatch(update.bind({heightMap:height,ht},{width:256}),[32,32,1]).dispatch(gradient.bind({h:height,slopeOut:slope},{width:256,height:256}),[32,32,1]).submit();await check(c,'height',height);await check(c,'slope',slope);}
 if(results.some(r=>r.maxError>1e-6))throw Error('Ocean pipeline exceeds native tolerance 1e-6');return {device:runtime.describe(),softwareAdapterRequested:false,intermediateReadbacks:'Validation only; no readback supplies later stage input',results};
 }finally{for(const b of [h0,ht,height,slope])runtime.destroyBuffer(b);}
}
