import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {compile} from '../src/compiler/compiler.js';import {executeCPU} from '../src/compiler/cpu-oracle.js';import {seedBuffer,validateConfig} from '../src/sandbox/config.js';
const source=fs.readFileSync(new URL('packed-uchar4.cu',import.meta.url),'utf8');
test('uchar4 packs four bytes per record and byte arithmetic follows integer promotion',()=>{const n=257,values=Float32Array.from({length:n},(_,i)=>(i*37)%256+.75),output=new Uint32Array(n*2+16).fill(0xdeadbeef),checks=new Int32Array(n),c=compile(source,{workgroupSize:[64]});executeCPU(c,{values,output,checks},{n},[5]);assert.equal(c.metadata.bindings.find(b=>b.name==='output').stride,4);for(let i=0;i<n;i++){const x=Math.trunc(values[i]),y=(i-130)&255,z=(i*17)&255;assert.equal(output[i*2],(x|(y<<8)|(z<<16)|(255<<24))>>>0);assert.equal(output[i*2+1],(((x+250)&255)|(((y-1)&255)<<8)|(((z+1)&255)<<16))>>>0);assert.equal(checks[i],-1700+x+4);}assert.ok(output.slice(n*2).every(x=>x===0xdeadbeef));assert.match(c.wgsl,/alias cw_uchar4 = u32/);});
test('Byte components can be read through buffer aliases and records copied in place',()=>{const c=compile('__global__ void k(uchar4* p,int* out){uchar4* a=p+1;uchar4 v=a[0];out[0]=v.w;out[1]=a[0].x;v.x=0;a[0]=v;}',{workgroupSize:[1]}),p=Uint32Array.from([0,0xff030201]),out=new Int32Array(2);executeCPU(c,{p,out},{},[1]);assert.deepEqual([...out],[255,1]);assert.equal(p[1],0xff030200);});
test('Packed image buffers seed and validate using unsigned words',()=>{const c=compile('__global__ void k(uchar4* out){out[0]=make_uchar4(1,2,3,4);}'),config={groups:[1,1,1],scalars:{},buffers:{out:{records:4,fill:'rgba',width:2}},output:'out',image:{width:2,height:2,format:'rgba8'}};assert.equal(validateConfig(config,c.metadata),16);assert.ok(seedBuffer(c.metadata.bindings[0],config.buffers.out) instanceof Uint32Array);});
test('Packed layout never silently widens byte storage or emits racy component stores',()=>{for(const source of ['__global__ void k(uchar* out){out[0]=1;}','__global__ void k(uchar x){}','__global__ void k(uchar4* out){__shared__ uchar4 p;p.x=1;out[0]=p;}','__global__ void k(uchar4* out){uchar4 a=make_uchar4(0,0,0,0);a+=a;out[0]=a;}','__global__ void k(uchar4* out){uchar4 a=make_uchar4(0,0,0,0);out[0]=a+a;}','__global__ void k(uint* out){uchar4 a=make_uchar4(0,0,0,0);out[0]=(uint)a;}'])assert.throws(()=>compile(source),/Byte pointers|Scalar kernel|component writes|uchar4|Cannot convert/);});

test('All original bicubic render entries retain four-byte output records',()=>{const source=fs.readFileSync(new URL('bicubic-texture-kernel.cuh',import.meta.url),'utf8');for(const entry of ['d_render','d_renderBicubic','d_renderFastBicubic','d_renderCatRom']){const c=compile(source,{entry,workgroupSize:[8,8,1]});assert.equal(c.metadata.bindings[0].elementType,'cw_uchar4');assert.equal(c.metadata.bindings[0].stride,4);assert.equal(c.metadata.textures[0].format,'r32float');assert.match(c.wgsl,/alias cw_uchar4 = u32/);}});

test('Byte fields in local structs declare packed aliases even without a byte local variable',()=>{const c=compile('struct Bytes{uchar a;uchar4 p;};__global__ void k(uint* out){Bytes b;b.a=258;b.p=make_uchar4(b.a,3,4,5);out[0]=b.p.y;}',{workgroupSize:[1]}),out=new Uint32Array(1);executeCPU(c,{out},{},[1]);assert.equal(out[0],3);assert.match(c.wgsl,/alias cw_uchar = u32/);assert.match(c.wgsl,/alias cw_uchar4 = u32/);});
