// SPDX-License-Identifier: MIT
#include <cuda_runtime.h>
#include <cooperative_groups.h>
#include <thrust/device_ptr.h>
#include <thrust/sort.h>
#include <vector>
#include <cstdio>
#include "helper_math.h"
#include "particle-collision-kernel.cuh"
#define CHECK(x) do{if((x)!=cudaSuccess){printf("CUDA failure %d\n",__LINE__);return 2;}}while(0)
bool save(const char*path,const void*data,size_t bytes){FILE*f=fopen(path,"wb");if(!f)return false;bool ok=fwrite(data,1,bytes,f)==bytes;fclose(f);return ok;}
int main(){for(int c=0;c<2;c++){unsigned n=c?257:128,cells=64*64*64;SimParams p={};p.gridSize=make_uint3(64);p.numCells=cells;p.numBodies=n;p.worldOrigin=make_float3(-1);p.particleRadius=1.f/64;p.cellSize=make_float3(1.f/32);p.colliderPos=make_float3(.12f,.12f,.12f);p.colliderRadius=.06f;p.spring=.5f;p.damping=.02f;p.shear=.1f;p.attraction=.001f;CHECK(cudaMemcpyToSymbol(cudaParams,&p,sizeof(p)));std::vector<float4> pos(n),vel(n);for(unsigned i=0;i<n;i++){pos[i]=make_float4((i%9)*.0265625f-.12f,((i/9)%9)*.0265625f-.12f,(i/81)*.0265625f-.04f,1);vel[i]=make_float4((int(i%7)-3)*.001f,(int(i%5)-2)*.001f,(int(i%3)-1)*.001f,0);}float4 *dp,*dv,*sp,*sv,*out;unsigned *hash,*index,*start,*end;CHECK(cudaMalloc(&dp,n*16));CHECK(cudaMalloc(&dv,n*16));CHECK(cudaMalloc(&sp,n*16));CHECK(cudaMalloc(&sv,n*16));CHECK(cudaMalloc(&out,n*16));CHECK(cudaMalloc(&hash,n*4));CHECK(cudaMalloc(&index,n*4));CHECK(cudaMalloc(&start,cells*4));CHECK(cudaMalloc(&end,cells*4));CHECK(cudaMemcpy(dp,pos.data(),n*16,cudaMemcpyHostToDevice));CHECK(cudaMemcpy(dv,vel.data(),n*16,cudaMemcpyHostToDevice));CHECK(cudaMemset(start,255,cells*4));CHECK(cudaMemset(end,0,cells*4));unsigned groups=(n+127)/128;calcHashD<<<groups,128>>>(hash,index,dp,n);CHECK(cudaGetLastError());thrust::sort_by_key(thrust::device_ptr<unsigned>(hash),thrust::device_ptr<unsigned>(hash+n),thrust::device_ptr<unsigned>(index));reorderDataAndFindCellStartD<<<groups,128,516>>>(start,end,sp,sv,hash,index,dp,dv,n);collideD<<<groups,128>>>(out,sp,sv,index,start,end,n);CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());void* buffers[]={hash,index,start,end,sp,sv,out};size_t sizes[]={n*4,n*4,cells*4,cells*4,n*16,n*16,n*16};const char*names[]={"hash","index","start","end","positions","velocities","collision"};for(int j=0;j<7;j++){std::vector<unsigned char> data(sizes[j]);CHECK(cudaMemcpy(data.data(),buffers[j],sizes[j],cudaMemcpyDeviceToHost));char path[128];snprintf(path,sizeof(path),"reports/particle-collision-%d-%s.bin",c,names[j]);if(!save(path,data.data(),sizes[j]))return 2;}for(void*b:buffers)CHECK(cudaFree(b));CHECK(cudaFree(dp));CHECK(cudaFree(dv));printf("PASS native particles: %u bodies, original hashes, Thrust sort, shared cell ranges and collisions.\n",n);}}
