// MIT validation host; NVIDIA device functions included unchanged.
#include <cuda_runtime.h>
#include <cooperative_groups.h>
#include <helper_image.h>
#include <vector>
#include <cstdio>
#include "postprocess-gl-kernel.cuh"
#define CHECK(x) do{auto e=(x);if(e!=cudaSuccess){printf("CUDA ERROR %s\n",cudaGetErrorString(e));return 2;}}while(0)
int main(){const int ws[]={8,32,32,32,512},hs[]={8,16,16,16,512},rs[]={0,1,4,8,4};const float thresholds[]={.8,.5,.8,0,.8},highlights[]={4,2,4,1.25,4};for(int k=0;k<5;k++){int w=ws[k],h=hs[k],r=rs[k];std::vector<float4> pixels(w*h);if(k==4){unsigned char* data=nullptr;unsigned pw,ph;if(!sdkLoadPPM4ub("showcases/postprocess-gl/teapot.ppm",&data,&pw,&ph)||pw!=w||ph!=h)return 2;for(int i=0;i<w*h;i++)pixels[i]=make_float4(data[i*4]/255.f,data[i*4+1]/255.f,data[i*4+2]/255.f,1);free(data);}else for(int i=0;i<w*h;i++)pixels[i]=make_float4((i*37)%256/255.f,(i*37+73)%256/255.f,(i*37+146)%256/255.f,1);
cudaArray_t array;auto channel=cudaCreateChannelDesc<float4>();CHECK(cudaMallocArray(&array,&channel,w,h));CHECK(cudaMemcpy2DToArray(array,0,0,pixels.data(),w*16,w*16,h,cudaMemcpyHostToDevice));cudaResourceDesc resource={};resource.resType=cudaResourceTypeArray;resource.res.array.array=array;cudaTextureDesc desc={};desc.filterMode=cudaFilterModePoint;desc.addressMode[0]=desc.addressMode[1]=cudaAddressModeClamp;desc.readMode=cudaReadModeElementType;cudaTextureObject_t tex;CHECK(cudaCreateTextureObject(&tex,&resource,&desc,nullptr));std::vector<unsigned> result(w*h+16,0xdeadbeef);unsigned* output;CHECK(cudaMalloc(&output,result.size()*4));CHECK(cudaMemcpy(output,result.data(),result.size()*4,cudaMemcpyHostToDevice));cudaProcess<<<dim3(w/8,h/8),dim3(8,8),(8+2*r)*(8+2*r)*4>>>(output,w,h,8+2*r,r,thresholds[k],highlights[k],tex);CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());CHECK(cudaMemcpy(result.data(),output,result.size()*4,cudaMemcpyDeviceToHost));for(int i=w*h;i<w*h+16;i++)if(result[i]!=0xdeadbeef)return 1;char path[128];snprintf(path,sizeof(path),"reports/postprocess-gl-native-%d.bin",k);FILE* f=fopen(path,"wb");if(!f||fwrite(result.data(),4,result.size(),f)!=result.size())return 2;fclose(f);printf("case=%d %dx%d radius=%d original kernel native capture PASS; guards unchanged\n",k,w,h,r);CHECK(cudaFree(output));CHECK(cudaDestroyTextureObject(tex));CHECK(cudaFreeArray(array));}return 0;}
