/** Mock GPU tests validate host orchestration only. These are not shader execution tests. */
import test from 'node:test';import assert from 'node:assert/strict';
import {GpuRuntime,Kernel} from '../src/runtime/runtime.js';import {compile} from '../src/compiler/compiler.js';
globalThis.GPUTextureUsage={COPY_DST:2,TEXTURE_BINDING:4,STORAGE_BINDING:8};
globalThis.GPUBufferUsage={MAP_READ:1,COPY_SRC:4,COPY_DST:8,UNIFORM:64,STORAGE:128,VERTEX:32,QUERY_RESOLVE:512};globalThis.GPUShaderStage={COMPUTE:4};
function setup(){
 const events=[],limits={minUniformBufferOffsetAlignment:256,maxTextureDimension2D:256,maxTextureDimension3D:256,maxComputeWorkgroupSizeX:256,maxComputeWorkgroupSizeY:256,maxComputeWorkgroupSizeZ:64,maxComputeInvocationsPerWorkgroup:256,maxComputeWorkgroupStorageSize:16384,maxStorageBuffersPerShaderStage:8,maxStorageBufferBindingSize:134217728,maxComputeWorkgroupsPerDimension:65535,maxUniformBufferBindingSize:65536};
 const device={limits,features:new Set(),lost:new Promise(()=>{}),addEventListener(){},removeEventListener(){},destroy(){},
 createBuffer(d){const buffer={size:d.size,usage:d.usage,bytes:new Uint8Array(d.size),destroyed:false,getMappedRange(){return this.bytes.buffer;},unmap(){},destroy(){this.destroyed=true;}};return buffer;},
 createTexture(d){return {...d,destroyed:false,createView(){return {};},destroy(){this.destroyed=true;}};},createSampler(d){return d;},
 createBindGroup(d){return d;},createBindGroupLayout(d){return d;},createPipelineLayout(d){return d;},createShaderModule(){return {getCompilationInfo:async()=>({messages:[]})};},createComputePipelineAsync:async d=>d,pushErrorScope(){},popErrorScope:async()=>null,
 queue:{writeTexture(destination,data,layout,size){events.push({kind:'textureUpload',bytes:data.byteLength,layout,size});},writeBuffer(buffer,offset,data,dataOffset=0,size){const src=ArrayBuffer.isView(data)?new Uint8Array(data.buffer,data.byteOffset+dataOffset,size):new Uint8Array(data,dataOffset,size);buffer.bytes.set(src,offset);events.push({kind:'upload',bytes:src.slice()});},submit(commands){events.push({kind:'submit',commands});},onSubmittedWorkDone:async()=>{}},
 createCommandEncoder(){const commands=[];return {beginComputePass(){return {setPipeline(p){commands.push({kind:'pipeline',p});},setBindGroup(index,group,offsets){commands.push({kind:'bind',group,offsets:[...offsets]});},dispatchWorkgroups(...groups){commands.push({kind:'dispatch',groups});},end(){commands.push({kind:'end'});}};},copyBufferToTexture(source,target,size){commands.push({kind:"textureCopy",source,target,size});},copyBufferToBuffer(source,sourceOffset,target,targetOffset,size){commands.push({kind:'copy',source,target,sourceOffset,targetOffset,size});},clearBuffer(buffer){commands.push({kind:'clear',buffer});},finish(){return commands;}};}};
 const runtime=new GpuRuntime(device);const artifact=compile('__global__ void stamp(float* values,unsigned int slot,float value){values[slot]=value;}');const kernel=new Kernel(runtime,artifact,{},{});const values=runtime.createBuffer(new Float32Array(4));
 return {runtime,kernel,values,events,device};
}
test('Each encoded scalar version receives a distinct aligned uniform snapshot',()=>{const {runtime,kernel,values,events}=setup();const inv=kernel.bind({values},{slot:0,value:11}),batch=runtime.batch();batch.dispatch(inv,[1]);inv.setScalars({slot:1,value:22});batch.dispatch(inv,[1]);batch.submit();const upload=events.find(e=>e.kind==='upload'),data=new DataView(upload.bytes.buffer);assert.equal(data.getFloat32(4,true),11);assert.equal(data.getFloat32(260,true),22);const commands=events.find(e=>e.kind==='submit').commands[0];assert.deepEqual(commands.filter(c=>c.kind==='bind').map(c=>c.offsets),[[0],[256]]);runtime.dispose();});
test('Repeated unchanged dispatches reuse bindings, pipeline and uniform slot',()=>{const {runtime,kernel,values,events}=setup();const inv=kernel.bind({values},{slot:0,value:1}),batch=runtime.batch();for(let i=0;i<20;i++)batch.dispatch(inv,[1]);batch.submit();const cmds=events.find(e=>e.kind==='submit').commands[0];assert.equal(cmds.filter(c=>c.kind==='pipeline').length,1);assert.equal(cmds.filter(c=>c.kind==='bind').length,1);assert.equal(cmds.filter(c=>c.kind==='dispatch').length,20);assert.equal(events.find(e=>e.kind==='upload').bytes.length,16);runtime.dispose();});
test('Interleaved recording then out-of-order submission preserves each batch data',()=>{const {runtime,kernel,values,events}=setup();const inv=kernel.bind({values},{slot:0,value:3}),a=runtime.batch();a.dispatch(inv,[1]);inv.setScalars({slot:1,value:7});const b=runtime.batch();b.dispatch(inv,[1]);b.submit();a.submit();const uploads=events.filter(e=>e.kind==='upload').map(e=>new DataView(e.bytes.buffer).getFloat32(4,true));assert.deepEqual(uploads,[7,3]);runtime.dispose();});
test('Invalid scalar updates preserve invocation values and version',()=>{const {runtime,kernel,values}=setup();const inv=kernel.bind({values},{slot:0,value:1}),version=inv.version;assert.throws(()=>inv.setScalars({value:2,slot:-1}));assert.equal(inv.version,version);assert.equal(inv.values.value,1);runtime.dispose();});
test('Writable aliasing across bindings is rejected',()=>{const {runtime,values}=setup();const artifact=compile('__global__ void k(const float* a,float* b){b[0]=a[0];}');const kernel=new Kernel(runtime,artifact,{},{});assert.throws(()=>kernel.bind({a:values,b:values}),/aliasing/);runtime.dispose();});
test('Destroyed buffers cannot be dispatched',()=>{const {runtime,kernel,values}=setup();const inv=kernel.bind({values},{slot:0,value:1});runtime.destroyBuffer(values);const batch=runtime.batch();assert.throws(()=>batch.dispatch(inv,[1]),/destroyed/);batch.discard();runtime.dispose();});
test('Zero workgroup counts are no-ops; oversized counts fail explicitly',()=>{const {runtime,kernel,values}=setup();const inv=kernel.bind({values},{slot:0,value:1}),batch=runtime.batch();batch.dispatch(inv,[0]);assert.equal(batch.dispatchCount,0);assert.throws(()=>batch.dispatch(inv,[65536]),/workgroup/);batch.discard();runtime.dispose();});
test('Submitted/discarded batches cannot be reused',()=>{const {runtime,kernel,values}=setup();const inv=kernel.bind({values},{slot:0,value:1}),batch=runtime.batch();batch.dispatch(inv,[1]);batch.submit();assert.throws(()=>batch.dispatch(inv,[1]),/submitted/);runtime.dispose();});
test('An imported buffer is borrowed, not destroyed by runtime cleanup',()=>{const {runtime,device}=setup();const external=device.createBuffer({size:16,usage:GPUBufferUsage.STORAGE});const imported=runtime.importBuffer(external);runtime.destroyBuffer(imported);runtime.dispose();assert.equal(external.destroyed,false);});
test('Pipeline cache deduplicates concurrent requests',async()=>{const {runtime}=setup();const source='__global__ void k(float* x){x[0]=1.0f;}';const [a,b]=await Promise.all([runtime.kernel(source),runtime.kernel(source)]);assert.equal(a,b);assert.equal(runtime.stats.pipelineCompiles,1);assert.equal(runtime.stats.pipelineCacheHits,1);runtime.dispose();});
test('Full uniform arena raises a clear error rather than overwriting an earlier snapshot',()=>{const {runtime,kernel,values}=setup();const inv=kernel.bind({values},{slot:0,value:1}),batch=runtime.batch();for(let i=0;i<256;i++){inv.setScalars({value:i});batch.dispatch(inv,[1]);}inv.setScalars({value:999});assert.throws(()=>batch.dispatch(inv,[1]),/arena is full/);batch.discard();runtime.dispose();});

test('GPU feedback copies end a compute pass and validate resource sizes',()=>{const {runtime,kernel,values,events}=setup(),target=runtime.createBuffer(16),short=runtime.createBuffer(4),batch=runtime.batch();batch.dispatch(kernel.bind({values},{slot:0,value:1}),[1]).copy(values,target).submit();const commands=events.find(e=>e.kind==='submit').commands[0];assert.ok(commands.findIndex(c=>c.kind==='copy')>commands.findIndex(c=>c.kind==='end'));const invalid=runtime.batch();assert.throws(()=>invalid.copy(values,values),/distinct/);assert.throws(()=>invalid.copy(values,short),/equal/);invalid.discard();assert.throws(()=>batch.copy(values,target),/submitted/);runtime.dispose();});

test('GPU range copies preserve offsets and reject unaligned or out-of-bounds ranges',()=>{const {runtime,values,events}=setup(),target=runtime.createBuffer(32),batch=runtime.batch();batch.copy(values,target,{sourceOffset:4,targetOffset:12,byteLength:8}).submit();const c=events.find(e=>e.kind==='submit').commands[0].find(c=>c.kind==='copy');assert.deepEqual([c.sourceOffset,c.targetOffset,c.size],[4,12,8]);const bad=runtime.batch();for(const range of [{sourceOffset:1,byteLength:4},{targetOffset:30,byteLength:4},{byteLength:20},{byteLength:-4},{sourceOffset:NaN,byteLength:4}])assert.throws(()=>bad.copy(values,target,range),/range/);bad.discard();runtime.dispose();});

test('3D texture creation validates byte volume shape and manages resource lifetime',()=>{const {runtime,events}=setup();assert.throws(()=>runtime.createTexture3D(new Uint8Array(8),{width:2,height:2,depth:3}),/matching byte/);assert.throws(()=>runtime.createTexture3D(new Uint8Array(8),{width:2,height:2,depth:2,filter:'cubic'}),/sampler/);const t=runtime.createTexture3D(new Uint8Array(8),{width:2,height:2,depth:2});assert.equal(events.find(e=>e.kind==='textureUpload').bytes,8);assert.throws(()=>runtime.destroyBuffer(t),/buffer resource/);runtime.destroyTexture(t);assert.equal(t.gpuTexture.destroyed,true);const other=runtime.createTexture3D(new Uint8Array(8),{width:2,height:2,depth:2});runtime.dispose();assert.equal(other.destroyed,true);});

test('Float4 transfer texture requires filtering support and keeps full float bytes',()=>{const {runtime,events,device}=setup();assert.throws(()=>runtime.createTexture1D(new Float32Array(8)),/float32-filterable/);device.features.add('float32-filterable');assert.throws(()=>runtime.createTexture1D(new Float32Array(3)),/float4/);assert.throws(()=>runtime.createTexture1D(Float32Array.from([NaN,0,0,0])),/finite/);const t=runtime.createTexture1D(Float32Array.from([.123456,0,0,1,.987654,1,1,0]));assert.equal(t.format,'rgba32float');assert.equal(t.dimension,'2d');assert.equal(events.find(e=>e.kind==='textureUpload').bytes,32);runtime.destroyTexture(t);runtime.dispose();});

test('Float 2D texture validates shape, precision and lifetime',()=>{const {runtime,events,device}=setup();const data=Float32Array.from([.123456,.987654,0,1]);assert.throws(()=>runtime.createTexture2D(data,{width:2,height:2}),/float32-filterable/);device.features.add('float32-filterable');for(const bad of [new Float32Array(3),Float32Array.from([NaN,0,0,0]),new Uint8Array(4)])assert.throws(()=>runtime.createTexture2D(bad,{width:2,height:2}),/finite floats/);const t=runtime.createTexture2D(data,{width:2,height:2});assert.equal(t.format,'r32float');assert.deepEqual(events.find(e=>e.kind==='textureUpload').layout,{bytesPerRow:8,rowsPerImage:2});runtime.destroyTexture(t);assert.equal(t.gpuTexture.destroyed,true);runtime.dispose();});

test('Writable surfaces allocate without uploading pixels and reject oversized dispatches',async()=>{const {runtime,device,events}=setup();device.features.add('float32-filterable');const source='__global__ void k(float* input,cudaSurfaceObject_t s){unsigned int x=blockIdx.x*blockDim.x+threadIdx.x;unsigned int y=blockIdx.y*blockDim.y+threadIdx.y;surf2Dwrite(input[y*8+x],s,x*4,y,cudaBoundaryModeTrap);}',kernel=await runtime.kernel(source,{workgroupSize:[8,8,1]}),input=runtime.createBuffer(new Float32Array(64)),surface=runtime.createTexture2D(null,{width:8,height:8,storage:true});assert.equal(events.filter(e=>e.kind==='textureUpload').length,0);assert.ok(surface.gpuTexture.usage&GPUTextureUsage.STORAGE_BINDING);const inv=kernel.bind({input,s:surface}),batch=runtime.batch();assert.throws(()=>batch.dispatch(inv,[2,1,1]),/Surface dispatch/);assert.throws(()=>batch.dispatch(inv,[1,1,2]),/Surface dispatch/);batch.dispatch(inv,[1,1,1]).submit();const plain=runtime.createTexture2D(new Float32Array(64),{width:8,height:8});assert.throws(()=>kernel.bind({input,s:plain}),/writable texture/);runtime.dispose();});

test('Pixel-coordinate textures preserve distinct coordinate scales and scalar snapshots',async()=>{const {runtime,device,events}=setup();device.features.add('float32-filterable');const kernel=await runtime.kernel('__global__ void k(float* out,cudaTextureObject_t a,cudaTextureObject_t b,float x){out[0]=tex2D<float>(a,x,0.5f)+tex2D<float>(b,x,0.5f);}');const a=runtime.createTexture2D(new Float32Array(32),{width:8,height:4,normalizedCoords:false,addressMode:'clamp-to-edge',filter:'nearest'}),b=runtime.createTexture2D(new Float32Array(32),{width:8,height:4}),out=runtime.createBuffer(new Float32Array(1)),inv=kernel.bind({out,a,b},{x:.5}),scales=kernel.artifact.metadata.textureScales;
assert.deepEqual(kernel.artifact.metadata.scalars.map(s=>s.name),['x']);for(const [i,expected]of [[0,[.125,.25]],[1,[1,1]]]){const view=new DataView(inv.uniformData);assert.equal(view.getFloat32(scales[i].offset,true),expected[0]);assert.equal(view.getFloat32(scales[i].offset+4,true),expected[1]);}assert.equal(new DataView(inv.uniformData).getFloat32(scales[0].pointOffset,true),1);assert.equal(new DataView(inv.uniformData).getFloat32(scales[1].pointOffset,true),0);const batch=runtime.batch().dispatch(inv,[1]);inv.setScalars({x:1.5});batch.dispatch(inv,[1]).submit();const upload=events.find(e=>e.kind==='upload'),view=new DataView(upload.bytes.buffer);assert.equal(view.getFloat32(0,true),.5);assert.equal(view.getFloat32(256,true),1.5);assert.equal(view.getFloat32(256+scales[0].offset,true),.125);assert.throws(()=>runtime.createTexture2D(new Float32Array(32),{width:8,height:4,normalizedCoords:false}),/clamp/);runtime.dispose();});
test('Packed buffer-to-texture copies support odd rows and reject invalid ranges',()=>{const {runtime,device,events}=setup();device.features.add('float32-filterable');const source=runtime.createBuffer(new Float32Array(128)),odd=runtime.createTexture2D(new Float32Array(15),{width:5,height:3}),aligned=runtime.createTexture2D(new Float32Array(128),{width:64,height:2});const batch=runtime.batch();for(const sourceOffset of [-4,2,500])assert.throws(()=>batch.copyToTexture(source,odd,{sourceOffset}));batch.copyToTexture(source,odd,{sourceOffset:4}).copyToTexture(source,aligned).submit();const copies=events.find(e=>e.kind==='submit').commands[0].filter(c=>c.kind==='textureCopy');assert.equal(copies.length,4);assert.deepEqual(copies.slice(0,3).map(c=>c.source.offset),[4,24,44]);assert.deepEqual(copies.slice(0,3).map(c=>c.target.origin),[[0,0,0],[0,1,0],[0,2,0]]);assert.equal(copies[3].source.bytesPerRow,256);runtime.dispose();});
test('RGBA 2D uploads count four components and reject invalid formats and payloads',()=>{const {runtime,device,events}=setup();device.features.add('float32-filterable');const r=runtime.createTexture2D(new Float32Array(24),{width:3,height:2,format:'rgba32float'});assert.equal(r.format,'rgba32float');assert.equal(events.find(e=>e.kind==='textureUpload').layout.bytesPerRow,48);for(const options of [{format:'bad'},{format:'rgba32float',storage:true}])assert.throws(()=>runtime.createTexture2D(new Float32Array(24),{width:3,height:2,...options}));assert.throws(()=>runtime.createTexture2D(new Float32Array(6),{width:3,height:2,format:'rgba32float'}));runtime.dispose();});
