/** Mock GPU tests validate host orchestration only. These are not shader execution tests. */
import test from 'node:test';import assert from 'node:assert/strict';
import {GpuRuntime,Kernel} from '../src/runtime/runtime.js';import {compile} from '../src/compiler/compiler.js';
globalThis.GPUBufferUsage={MAP_READ:1,COPY_SRC:4,COPY_DST:8,UNIFORM:64,STORAGE:128,VERTEX:32,QUERY_RESOLVE:512};globalThis.GPUShaderStage={COMPUTE:4};
function setup(){
 const events=[],limits={minUniformBufferOffsetAlignment:256,maxComputeWorkgroupSizeX:256,maxComputeWorkgroupSizeY:256,maxComputeWorkgroupSizeZ:64,maxComputeInvocationsPerWorkgroup:256,maxComputeWorkgroupStorageSize:16384,maxStorageBuffersPerShaderStage:8,maxStorageBufferBindingSize:134217728,maxComputeWorkgroupsPerDimension:65535,maxUniformBufferBindingSize:65536};
 const device={limits,features:new Set(),lost:new Promise(()=>{}),addEventListener(){},removeEventListener(){},destroy(){},
 createBuffer(d){const buffer={size:d.size,usage:d.usage,bytes:new Uint8Array(d.size),destroyed:false,getMappedRange(){return this.bytes.buffer;},unmap(){},destroy(){this.destroyed=true;}};return buffer;},
 createBindGroup(d){return d;},createBindGroupLayout(d){return d;},createPipelineLayout(d){return d;},createShaderModule(){return {getCompilationInfo:async()=>({messages:[]})};},createComputePipelineAsync:async d=>d,pushErrorScope(){},popErrorScope:async()=>null,
 queue:{writeBuffer(buffer,offset,data,dataOffset=0,size){const src=ArrayBuffer.isView(data)?new Uint8Array(data.buffer,data.byteOffset+dataOffset,size):new Uint8Array(data,dataOffset,size);buffer.bytes.set(src,offset);events.push({kind:'upload',bytes:src.slice()});},submit(commands){events.push({kind:'submit',commands});},onSubmittedWorkDone:async()=>{}},
 createCommandEncoder(){const commands=[];return {beginComputePass(){return {setPipeline(p){commands.push({kind:'pipeline',p});},setBindGroup(index,group,offsets){commands.push({kind:'bind',group,offsets:[...offsets]});},dispatchWorkgroups(...groups){commands.push({kind:'dispatch',groups});},end(){commands.push({kind:'end'});}};},copyBufferToBuffer(source,sourceOffset,target,targetOffset,size){commands.push({kind:'copy',source,target,size});},clearBuffer(buffer){commands.push({kind:'clear',buffer});},finish(){return commands;}};}};
 const runtime=new GpuRuntime(device);const artifact=compile('__global__ void stamp(float* values,unsigned int slot,float value){values[slot]=value;}');const kernel=new Kernel(runtime,artifact,{},{});const values=runtime.createBuffer(new Float32Array(4));
 return {runtime,kernel,values,events,device};
}
test('Each encoded scalar version receives a distinct aligned uniform snapshot',()=>{const {runtime,kernel,values,events}=setup();const inv=kernel.bind({values},{slot:0,value:11}),batch=runtime.batch();batch.dispatch(inv,[1]);inv.setScalars({slot:1,value:22});batch.dispatch(inv,[1]);batch.submit();const upload=events.find(e=>e.kind==='upload'),data=new DataView(upload.bytes.buffer);assert.equal(data.getFloat32(4,true),11);assert.equal(data.getFloat32(260,true),22);const commands=events.find(e=>e.kind==='submit').commands[0];assert.deepEqual(commands.filter(c=>c.kind==='bind').map(c=>c.offsets),[[0],[256]]);runtime.dispose();});
test('Repeated unchanged dispatches reuse bindings, pipeline and uniform slot',()=>{const {runtime,kernel,values,events}=setup();const inv=kernel.bind({values},{slot:0,value:1}),batch=runtime.batch();for(let i=0;i<20;i++)batch.dispatch(inv,[1]);batch.submit();const cmds=events.find(e=>e.kind==='submit').commands[0];assert.equal(cmds.filter(c=>c.kind==='pipeline').length,1);assert.equal(cmds.filter(c=>c.kind==='bind').length,1);assert.equal(cmds.filter(c=>c.kind==='dispatch').length,20);assert.equal(events.find(e=>e.kind==='upload').bytes.length,16);runtime.dispose();});
test('Interleaved recording then out-of-order submission preserves each batch data',()=>{const {runtime,kernel,values,events}=setup();const inv=kernel.bind({values},{slot:0,value:3}),a=runtime.batch();a.dispatch(inv,[1]);inv.setScalars({slot:1,value:7});const b=runtime.batch();b.dispatch(inv,[1]);b.submit();a.submit();const uploads=events.filter(e=>e.kind==='upload').map(e=>new DataView(e.bytes.buffer).getFloat32(4,true));assert.deepEqual(uploads,[7,3]);runtime.dispose();});
test('Invalid scalar updates preserve invocation values and version',()=>{const {runtime,kernel,values}=setup();const inv=kernel.bind({values},{slot:0,value:1}),version=inv.version;assert.throws(()=>inv.setScalars({value:2,slot:-1}));assert.equal(inv.version,version);assert.equal(inv.values.value,1);runtime.dispose();});
test('Writable aliasing across bindings is rejected',()=>{const {runtime,values}=setup();const artifact=compile('__global__ void k(const float* a,float* b){b[0]=a[0];}');const kernel=new Kernel(runtime,artifact,{},{});assert.throws(()=>kernel.bind({a:values,b:values}),/aliasing/);runtime.dispose();});
test('Destroyed buffers cannot be dispatched',()=>{const {runtime,kernel,values}=setup();const inv=kernel.bind({values},{slot:0,value:1});runtime.destroyBuffer(values);const batch=runtime.batch();assert.throws(()=>batch.dispatch(inv,[1]),/destroyed/);batch.discard();runtime.dispose();});
test('Zero workgroup counts are no-ops; oversized counts fail explicitly',()=>{const {runtime,kernel,values}=setup();const inv=kernel.bind({values},{slot:0,value:1}),batch=runtime.batch();batch.dispatch(inv,[0]);assert.equal(batch.dispatchCount,0);assert.throws(()=>batch.dispatch(inv,[65536]),/workgroup/);batch.discard();runtime.dispose();});
test('Submitted/discarded batches cannot be reused',()=>{const {runtime,kernel,values}=setup();const inv=kernel.bind({values},{slot:0,value:1}),batch=runtime.batch();batch.dispatch(inv,[1]);batch.submit();assert.throws(()=>batch.dispatch(inv,[1]),/submitted/);runtime.dispose();});
test('An imported buffer is borrowed, not destroyed by runtime cleanup',()=>{const {runtime,device}=setup();const external=device.createBuffer({size:16,usage:GPUBufferUsage.STORAGE});const imported=runtime.importBuffer(external);runtime.destroyBuffer(imported);runtime.dispose();assert.equal(external.destroyed,false);});
test('Pipeline cache deduplicates concurrent requests',async()=>{const {runtime}=setup();const source='__global__ void k(float* x){x[0]=1.0f;}';const [a,b]=await Promise.all([runtime.kernel(source),runtime.kernel(source)]);assert.equal(a,b);assert.equal(runtime.stats.pipelineCompiles,1);assert.equal(runtime.stats.pipelineCacheHits,1);runtime.dispose();});
test('Full uniform arena raises a clear error rather than overwriting an earlier snapshot',()=>{const {runtime,kernel,values}=setup();const inv=kernel.bind({values},{slot:0,value:1}),batch=runtime.batch();for(let i=0;i<256;i++){inv.setScalars({value:i});batch.dispatch(inv,[1]);}inv.setScalars({value:999});assert.throws(()=>batch.dispatch(inv,[1]),/arena is full/);batch.discard();runtime.dispose();});

test('GPU feedback copies end a compute pass and validate resource sizes',()=>{const {runtime,kernel,values,events}=setup(),target=runtime.createBuffer(16),short=runtime.createBuffer(4),batch=runtime.batch();batch.dispatch(kernel.bind({values},{slot:0,value:1}),[1]).copy(values,target).submit();const commands=events.find(e=>e.kind==='submit').commands[0];assert.ok(commands.findIndex(c=>c.kind==='copy')>commands.findIndex(c=>c.kind==='end'));const invalid=runtime.batch();assert.throws(()=>invalid.copy(values,values),/distinct/);assert.throws(()=>invalid.copy(values,short),/equal/);invalid.discard();assert.throws(()=>batch.copy(values,target),/submitted/);runtime.dispose();});
