import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {compile} from '../src/compiler/compiler.js';import {executeCPU} from '../src/compiler/cpu-oracle.js';
const source=['marching-cross.cuh','shared-pointer.cu'].map(f=>readFileSync(new URL(f,import.meta.url),'utf8')).join('\n');
test('Shared pointer helpers preserve original normals, aliases, offset updates and forwarding',()=>{const a=compile(source,{entry:'sharedPointers',workgroupSize:[32,1,1]}),output=new Float32Array(96*12);executeCPU(a,{output},{},[3]);assert.equal(a.metadata.workgroupStorageBytes,1536);for(let i=0;i<96;i++)assert.deepEqual([...output.slice(i*12,i*12+12)],[0,0,2,0,i+1,i+1,0,1,i+1,0,2,1]);});
test('Shared pointer helpers reject atomic arrays, type mismatches and const discards',()=>{for(const s of ['__device__ void f(float* p){p[0]=1;} __global__ void k(){__shared__ uint a[2];f(a);}','__device__ void f(uint* p){p[0]=1;} __global__ void k(){__shared__ uint a[2];atomicAdd(&a[0],1);f(a);}','__device__ void g(float* p){p[0]=1;} __device__ void f(const float* p){g(p);} __global__ void k(){__shared__ float a[2];f(a);}'])assert.throws(()=>compile(s),/Shared pointer type|atomic arrays|discard const/);});
test('Pointer slots retain evaluated offsets while targets change and support dynamic selection',()=>{const a=compile('__global__ void k(float* out){__shared__ float s[4];uint i=threadIdx.x;s[i]=float(i);__syncthreads();float* p[2];uint j=i;p[0]=&s[j];j=(j+1u)%4u;p[1]=&s[j];*p[0]=float(i)+10.0f;__syncthreads();out[i]=*p[i%2u];}',{workgroupSize:[4,1,1]}),out=new Float32Array(4);executeCPU(a,{out},{},[1]);assert.deepEqual([...out],[10,12,12,10]);});
test('Pointer arrays reject unbound, mixed-allocation, local and mismatched addresses',()=>{for(const body of ['float* p[2];out[0]=*p[0];','__shared__ float a[2];__shared__ float b[2];float* p[2];p[0]=&a[0];p[1]=&b[0];','float a[2];float* p[2];p[0]=&a[0];','__shared__ uint a[2];float* p[2];p[0]=&a[0];','float* p[257];'])assert.throws(()=>compile('__global__ void k(float* out){'+body+'}'),/Pointer array|pointer array/);});
test('Original sampled-volume triangle entry compiles with shared pointer slots',()=>{const source=['marching-lerp.cuh','marching-cross.cuh','marching-cubes-kernel.cuh'].map(f=>readFileSync(new URL(f,import.meta.url),'utf8')).join('\n'),a=compile(source,{entry:'generateTriangles2',workgroupSize:[32,1,1],defines:{_DEFINES_H_:1,SAMPLE_VOLUME:1,USE_SHARED:1,NTHREADS:32,SKIP_EMPTY_VOXELS:1}});assert.equal(a.metadata.workgroupStorageBytes,6144);assert.match(a.wgsl,/var v_v: array<i32, 3>/);});

test('Local shared aliases capture chained offsets and forward mutable pointees',()=>{const source='__device__ void f(float* p){float* q=p+2-1;*q=*p+10.0f;}__global__ void k(float*out){__shared__ float s[16];unsigned i=threadIdx.x;s[4*i]=float(i);s[4*i+1]=0.0f;__syncthreads();unsigned offset=4*i;float* p=s+offset+2-2;offset=0;f(p+2-2);out[i]=p[1];}';const a=compile(source,{workgroupSize:[4,1,1]}),out=new Float32Array(4);executeCPU(a,{out},{},[1]);assert.deepEqual([...out],[10,11,12,13]);});
test('Local shared aliases reject atomic storage and const removal',()=>{for(const s of ['__global__ void k(){__shared__ uint s[4];atomicAdd(&s[0],1);uint* p=s;}','__global__ void k(){__shared__ float s[4];const float* p=s;float* q=p;}'])assert.throws(()=>compile(s),/non-atomic|discard const/);});

test('Volatile shared pointer slots retain offsets and communicate across lanes',()=>{const source=readFileSync(new URL('volatile-pointer.cu',import.meta.url),'utf8'),a=compile(source,{workgroupSize:[32],sharedMemoryBytes:512}),out=new Int32Array(128);executeCPU(a,{out},{},[1]);for(let i=0;i<32;i++)for(let q=0;q<4;q++)assert.equal(out[i*4+q],q*100+(i+1)%32);assert.match(a.wgsl,/array<atomic<i32>, 128>/);assert.match(a.wgsl,/atomicLoad/);assert.match(a.wgsl,/atomicStore/);});
test('Volatile pointer slots reject local allocations, type changes and qualifier removal',()=>{for(const body of ['int s[4];volatile int*p[1];p[0]=(volatile int*)&s[0];','__shared__ float s[4];volatile int*p[1];p[0]=(volatile int*)&s[0];','__shared__ int s[4];int*p[1];p[0]=(volatile int*)&s[0];'])assert.throws(()=>compile('__global__ void k(){'+body+'}'),/Pointer array|Pointer arrays|Shared atomics/);});
