import {readFileSync} from 'node:fs';
import test from 'node:test';import assert from 'node:assert/strict';import {compile} from '../src/compiler/compiler.js';import {executeCPU} from '../src/compiler/cpu-oracle.js';
test('sincos outputs preserve the original NVIDIA twiddle component order through references',()=>{const a=compile('__device__ void getTwiddle(float2 &twiddle,float phase){__sincosf(phase,&twiddle.y,&twiddle.x);} __global__ void k(float2*out){float2 v;getTwiddle(v,0.75f);out[0]=v;}'),out=new Float32Array(2);executeCPU(a,{out},{},[1]);assert.deepEqual([...out],[Math.fround(Math.cos(.75)),Math.fround(Math.sin(.75))]);});
test('sincos captures phase once before either output changes it',()=>{for(const name of ['sincosf','__sincosf']){const a=compile(`__global__ void k(float*out){float s=.5f,c;${name}(s,&s,&c);out[0]=s;out[1]=c;}`),out=new Float32Array(2);executeCPU(a,{out},{},[1]);assert.deepEqual([...out],[Math.fround(Math.sin(.5)),Math.fround(Math.cos(.5))]);}});
test('sincos rejects invalid destinations, aliasing, types and arity',()=>{for(const body of ['float s,c;__sincosf(0,s,&c);','float s;__sincosf(0,&s,&s);','float s;int c;__sincosf(0,&s,&c);','const float s=0;float c;__sincosf(0,&s,&c);','float c;__sincosf(0,&out[0],&c);','float s,c;__sincosf(0,&s);'])assert.throws(()=>compile('__global__ void k(float*out){'+body+'}'));});

test('__ffs returns one-based bit positions for every bit, signed values and zero',()=>{const a=compile('__global__ void k(int*input,int*out,unsigned n){unsigned i=blockIdx.x*blockDim.x+threadIdx.x;if(i<n)out[i]=__ffs(input[i]);}'),input=Int32Array.from([0,...Array.from({length:32},(_,i)=>1<<i),-1,-8,0x123400]),out=new Int32Array(input.length);executeCPU(a,{input,out},{n:input.length},[input.length]);assert.deepEqual([...out],[0,...Array.from({length:32},(_,i)=>i+1),1,4,11]);});

test('Original custom FFT kernels compile with macro type aliases, first-bit division and sincos references',()=>{const source=readFileSync('tests/fft-convolution-custom-kernels.cuh','utf8');for(const entry of ['spPostprocess2D_kernel','spPreprocess2D_kernel','spProcess2D_kernel']){const a=compile(source,{entry,workgroupSize:[256,1,1]});assert.ok(a.wgsl.includes('firstTrailingBit'));assert.ok(a.metadata.textures.every(t=>t.format==='rg32float'));}});
