import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {compile} from '../src/compiler/compiler.js';import {executeCPU} from '../src/compiler/cpu-oracle.js';import {kernelSource} from '../src/sandbox/import.js';
const source=fs.readFileSync(new URL('volume-convert-kernel.cuh',import.meta.url),'utf8');
test('Original NVIDIA static conversion preserves double product at byte boundaries',()=>{const inputBytes=fs.readFileSync(new URL('../reports/volume-convert-input.bin',import.meta.url)),input=new Float32Array(inputBytes.buffer.slice(inputBytes.byteOffset,inputBytes.byteOffset+inputBytes.byteLength)),output=new Uint32Array(input.length+16).fill(0xdeadbeef),a=compile(source,{defines:{__CUDACC__:1},entry:'conversionProbe',workgroupSize:[64]});executeCPU(a,{input,output},{n:input.length},[Math.ceil(input.length/64)]);let differences=0;for(let i=0;i<input.length;i++){const value=Math.max(0,Math.min(1,input[i]));assert.equal(output[i],Math.trunc(value*255));if(Math.trunc(Math.fround(value*255))!==output[i])differences++;}assert.equal(differences,0);assert.ok(output.slice(input.length).every(x=>x===0xdeadbeef));assert.match(a.wgsl,/cw_exact_byte_scale/);});
test('Static template primary and specialized methods use their own signatures',()=>{const s='template<class T> struct A{static __device__ T convert(T x){return T(x+x);}};template<> struct A<int>{static __device__ int convert(int x){return x+3;}};__global__ void k(float* out){out[0]=A<float>::convert(2.0f);out[1]=(float)A<int>::convert(2);}';const a=compile(s,{workgroupSize:[1]}),out=new Float32Array(2);executeCPU(a,{out},{},[1]);assert.deepEqual([...out],[4,5]);});
test('Static methods reject recursion, missing specializations, data access and selected unsupported types',()=>{for(const s of ['template<class T> struct A{};__global__ void k(){A<float>::missing(1);}','template<class T> struct A{static __device__ T f(T x){return A<float>::f(x);}};__global__ void k(){A<float>::f(1.0f);}','template<class T> struct A{static const int x=2;};__global__ void k(int* out){out[0]=A<float>::x;}','template<class T> struct A{};template<> struct A<double>{static __device__ double f(double x){return x;}};__global__ void k(){A<double>::f(1.0);}'])assert.throws(()=>compile(s));});
test('Desktop import preserves static template wrappers and method bodies',()=>{const s='#include <cuda_runtime.h>\ntemplate<class T> struct A{};\ntemplate<> struct A<float>{static const int mode=2;static __device__ float f(float x){return x;}};\n__global__ void k(float* out){out[0]=A<float>::f(1.0f);}';const result=kernelSource(s);assert.ok(result.source.includes(s.slice(s.indexOf('template<class'))));compile(result.source);});

test('Exact double-literal byte scaling avoids rounding up at integer boundaries',()=>{const input=Float32Array.from({length:255},(_,i)=>(i+1)/65535),output=new Uint32Array(255),a=compile(source,{entry:'scaleProbe',defines:{__CUDACC__:1},workgroupSize:[64]});executeCPU(a,{input,output},{n:255},[4]);let differences=0;for(let i=0;i<255;i++){assert.equal(output[i],Math.trunc(input[i]*65535));if(Math.trunc(Math.fround(input[i]*65535))!==output[i])differences++;}assert.equal(differences,255);});

test('Static specializations cannot replace an already instantiated primary',()=>{assert.throws(()=>compile('template<class T> struct A{static __device__ T f(T x){return x;}};__global__ void k(float* out){out[0]=A<float>::f(1.0f);}template<> struct A<float>{static __device__ float f(float x){return 2.0f;}};'),/precede their first use/);});
test('Double-to-byte casts stay rejected outside the exact byte-scale profile',()=>{for(const expression of ['(unsigned char)(x*1.5)','(unsigned char)(x*65536.0)'])assert.throws(()=>compile('__global__ void k(float x,uint* out){out[0]='+expression+';}'),/Cannot convert cw_f64/);});

test('Static member names cannot silently bind to unrelated global functions',()=>{assert.throws(()=>compile('__device__ float f(float x){return 99.0f;}template<class T> struct A{static __device__ T f(T x){return x;}static __device__ T g(T x){return f(x);}};__global__ void k(float* out){out[0]=A<float>::g(1.0f);}'),/Unqualified static member/);});
