// MIT validation host. Original NVIDIA functions and image retain BSD notice.
#include <cuda_runtime.h>
#include <helper_image.h>
#include <vector>
#include <cmath>
#include <cstdio>
#include "surface-write-kernel.cuh"
#define CHECK(x) do{auto e=(x);if(e!=cudaSuccess){printf("CUDA ERROR %s\n",cudaGetErrorString(e));return 2;}}while(0)
int main(){float* data=nullptr;unsigned w,h;if(!sdkLoadPGM("showcases/surface-write/teapot512.pgm",&data,&w,&h)||w!=512||h!=512)return 2;size_t count=w*h;float *input,*output;CHECK(cudaMalloc(&input,count*4));CHECK(cudaMalloc(&output,(count+16)*4));CHECK(cudaMemcpy(input,data,count*4,cudaMemcpyHostToDevice));cudaArray_t array;auto channel=cudaCreateChannelDesc<float>();CHECK(cudaMallocArray(&array,&channel,w,h,cudaArraySurfaceLoadStore));cudaResourceDesc resource={};resource.resType=cudaResourceTypeArray;resource.res.array.array=array;cudaSurfaceObject_t surface;CHECK(cudaCreateSurfaceObject(&surface,&resource));cudaTextureDesc desc={};desc.normalizedCoords=1;desc.filterMode=cudaFilterModeLinear;desc.addressMode[0]=desc.addressMode[1]=cudaAddressModeWrap;desc.readMode=cudaReadModeElementType;cudaTextureObject_t texture;CHECK(cudaCreateTextureObject(&texture,&resource,&desc,nullptr));
surfaceWriteKernel<<<dim3(w/8,h/8),dim3(8,8)>>>(input,w,h,surface);CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());std::vector<float> written(count);CHECK(cudaMemcpy2DFromArray(written.data(),w*4,array,0,0,w*4,h,cudaMemcpyDeviceToHost));for(size_t i=0;i<count;i++)if(written[i]!=data[i]){printf("FAIL surface pixel %zu\n",i);return 1;}printf("PASS original surface writer: all %zu texels exactly equal input\n",count);
for(int scenario=0;scenario<3;scenario++){float theta=scenario==0?.5f:scenario==1?0.f:-.7f;std::vector<float> result(count+16,-12345);CHECK(cudaMemcpy(output,result.data(),result.size()*4,cudaMemcpyHostToDevice));transformKernel<<<dim3(w/8,h/8),dim3(8,8)>>>(output,w,h,theta,texture);CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());CHECK(cudaMemcpy(result.data(),output,result.size()*4,cudaMemcpyDeviceToHost));for(size_t i=0;i<result.size();i++)if(i<count?!std::isfinite(result[i]):result[i]!=-12345)return 1;char path[128];snprintf(path,sizeof(path),"reports/surface-write-native-%d.bin",scenario);FILE* file=fopen(path,"wb");if(!file||fwrite(result.data(),4,result.size(),file)!=result.size())return 2;fclose(file);printf("scenario=%d theta=%g PASS original surface/texture pipeline, finite output and guards\n",scenario,theta);}
CHECK(cudaDestroyTextureObject(texture));CHECK(cudaDestroySurfaceObject(surface));CHECK(cudaFreeArray(array));CHECK(cudaFree(input));CHECK(cudaFree(output));free(data);return 0;}
