// MIT validation host. NVIDIA device code and input retain their BSD notice.
#include <cuda_runtime.h>
#include <helper_image.h>
#include <vector>
#include <cmath>
#include <cstdio>
#include "texture2d-kernel.cuh"
#define CHECK(x) do{auto e=(x);if(e!=cudaSuccess){printf("CUDA ERROR %s\n",cudaGetErrorString(e));return 2;}}while(0)
int main(){float* data=nullptr;unsigned w,h;if(!sdkLoadPGM("showcases/texture2d/teapot512.pgm",&data,&w,&h)||w!=512||h!=512)return 2;
 cudaArray_t array;auto channel=cudaCreateChannelDesc<float>();CHECK(cudaMallocArray(&array,&channel,w,h));CHECK(cudaMemcpy2DToArray(array,0,0,data,w*4,w*4,h,cudaMemcpyHostToDevice));float* output;const size_t count=w*h;CHECK(cudaMalloc(&output,(count+16)*4));
 for(int scenario=0;scenario<4;scenario++){const float angle=scenario==0?.5f:scenario==1?0.f:scenario==2?-.7f:.5f;const bool linear=scenario!=3;cudaResourceDesc resource={};resource.resType=cudaResourceTypeArray;resource.res.array.array=array;cudaTextureDesc desc={};desc.normalizedCoords=1;desc.filterMode=linear?cudaFilterModeLinear:cudaFilterModePoint;desc.addressMode[0]=desc.addressMode[1]=cudaAddressModeWrap;desc.readMode=cudaReadModeElementType;cudaTextureObject_t texture;CHECK(cudaCreateTextureObject(&texture,&resource,&desc,nullptr));std::vector<float> result(count+16,-12345);CHECK(cudaMemcpy(output,result.data(),result.size()*4,cudaMemcpyHostToDevice));transformKernel<<<dim3(w/8,h/8),dim3(8,8)>>>(output,w,h,angle,texture);CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());CHECK(cudaMemcpy(result.data(),output,result.size()*4,cudaMemcpyDeviceToHost));float maxError=0;unsigned boundaryPixels=0;auto at=[&](int x,int y){return data[((y%int(h)+h)%h)*w+(x%int(w)+w)%w];};
 for(size_t i=0;i<result.size();i++){if(i>=count){if(result[i]!=-12345)return 1;continue;}const double u=int(i%w)-double(w)/2,v=int(i/w)-double(h)/2;double x=u*cos(double(angle))-v*sin(double(angle))+w/2.,y=v*cos(double(angle))+u*sin(double(angle))+h/2.,expected;if(linear){x-=.5;y-=.5;const int ix=int(floor(x)),iy=int(floor(y));const double fx=x-ix,fy=y-iy;expected=(at(ix,iy)*(1-fx)+at(ix+1,iy)*fx)*(1-fy)+(at(ix,iy+1)*(1-fx)+at(ix+1,iy+1)*fx)*fy;}else expected=at(int(floor(x)),int(floor(y)));float error=std::abs(result[i]-expected);maxError=std::max(maxError,error);bool acceptable=linear?error<=.005f:error==0;if(!linear&&error!=0){const bool bx=std::abs(x-round(x))<.001,by=std::abs(y-round(y))<.001;bool matches=false;for(int dy=0;dy<=(by?1:0);dy++)for(int dx=0;dx<=(bx?1:0);dx++)if(result[i]==at(bx?int(round(x))-1+dx:int(floor(x)),by?int(round(y))-1+dy:int(floor(y))))matches=true;acceptable=(bx||by)&&matches;if(acceptable)boundaryPixels++;}if(!std::isfinite(result[i])||!acceptable){printf("FAIL independent reference pixel=%zu error=%g\n",i,error);return 1;}}
 char path[128];snprintf(path,sizeof(path),"reports/texture2d-native-%d.bin",scenario);FILE* file=fopen(path,"wb");if(!file||fwrite(result.data(),4,result.size(),file)!=result.size())return 2;fclose(file);printf("scenario=%d theta=%g %s PASS all %zu pixels, independent sampling reference and guards; max error %g; boundary choices %u\n",scenario,angle,linear?"linear":"nearest",count,maxError,boundaryPixels);CHECK(cudaDestroyTextureObject(texture));}
 CHECK(cudaFree(output));CHECK(cudaFreeArray(array));free(data);return 0;}
