import {decodePGM} from '../src/sandbox/pgm.js';
export async function checkTexture2D(runtime){
 const source=await(await fetch('/tests/texture2d-kernel.cuh')).text(),kernel=await runtime.kernel(source,{workgroupSize:[8,8,1]}),image=decodePGM(new Uint8Array(await(await fetch('/showcases/texture2d/teapot512.pgm')).arrayBuffer())),comparisons=[];
 for(let scenario=0;scenario<4;scenario++){
  const theta=[.5,0,-.7,.5][scenario],filter=scenario===3?'nearest':'linear',texture=runtime.createTexture2D(image.data,{width:image.width,height:image.height,filter}),initial=new Float32Array(image.data.length+16).fill(-12345),output=runtime.createBuffer(initial);
  try{runtime.batch().dispatch(kernel.bind({outputData:output,tex:texture},{width:image.width,height:image.height,theta}),[image.width/8,image.height/8,1]).submit();const actual=await runtime.read(output),expected=new Float32Array(await(await fetch('/reports/texture2d-native-'+scenario+'.bin')).arrayBuffer());if(expected.length!==actual.length)throw Error('Native texture image size mismatch');let maxError=0,boundaryPixels=0;for(let i=0;i<actual.length;i++){if(i>=image.data.length){if(actual[i]!==-12345)throw Error('Texture rotation guard changed');continue;}const error=Math.abs(actual[i]-expected[i]);maxError=Math.max(maxError,error);if(filter==='nearest'&&error!==0){const u=i%image.width-image.width/2,v=Math.floor(i/image.width)-image.height/2,x=u*Math.cos(theta)-v*Math.sin(theta)+image.width/2,y=v*Math.cos(theta)+u*Math.sin(theta)+image.height/2,indices=c=>Math.abs(c-Math.round(c))<.001?[Math.round(c)-1,Math.round(c)]:[Math.floor(c)],xs=indices(x),ys=indices(y),values=ys.flatMap(y=>xs.map(x=>image.data[((y%image.height+image.height)%image.height)*image.width+(x%image.width+image.width)%image.width]));if((xs.length===1&&ys.length===1)||!values.some(v=>v===actual[i])||!values.some(v=>v===expected[i]))throw Error('Nearest rotation differs away from a rounding boundary at '+i);boundaryPixels++;}else if(!Number.isFinite(actual[i])||error>.005)throw Error(`Texture rotation mismatch scenario=${scenario} pixel=${i} error=${error}`);}comparisons.push({scenario,theta,filter,maxError,boundaryPixels,pixels:image.data.length});}
  finally{runtime.destroyTexture(texture);runtime.destroyBuffer(output);}
 }
 return {comparisons};
}
