// MIT probe for native CUDA volume + float4 transfer texture sampling.
#include <cuda_runtime.h>
#include <cstdio>
#include <cmath>
#include <algorithm>
#include "transfer-texture.cu"
#define CHECK(x) do{auto e=(x);if(e!=cudaSuccess){printf("CUDA ERROR %s\n",cudaGetErrorString(e));return 2;}}while(0)
int main(){const float coords[]={-.2f,0,.0625f,.13f,.5f,.875f,1,1.2f},values[]={0,0,0,0,1,.25f,0,1,0,1,.5f,.75f,.2f,.4f,1,.5f};unsigned char voxels[8];std::fill(voxels,voxels+8,128);cudaArray_t volumeArray,transferArray;auto vc=cudaCreateChannelDesc<unsigned char>(),tc=cudaCreateChannelDesc<float4>();CHECK(cudaMalloc3DArray(&volumeArray,&vc,make_cudaExtent(2,2,2)));cudaMemcpy3DParms copy={};copy.srcPtr=make_cudaPitchedPtr(voxels,2,2,2);copy.dstArray=volumeArray;copy.extent=make_cudaExtent(2,2,2);copy.kind=cudaMemcpyHostToDevice;CHECK(cudaMemcpy3D(&copy));CHECK(cudaMallocArray(&transferArray,&tc,4,1));CHECK(cudaMemcpy2DToArray(transferArray,0,0,values,sizeof(values),sizeof(values),1,cudaMemcpyHostToDevice));cudaResourceDesc resource={};resource.resType=cudaResourceTypeArray;resource.res.array.array=volumeArray;cudaTextureDesc desc={};desc.normalizedCoords=1;desc.filterMode=cudaFilterModeLinear;desc.readMode=cudaReadModeNormalizedFloat;cudaTextureObject_t volume;CHECK(cudaCreateTextureObject(&volume,&resource,&desc,nullptr));float* coordinates;float4* output;CHECK(cudaMalloc(&coordinates,sizeof(coords)));CHECK(cudaMalloc(&output,128));CHECK(cudaMemcpy(coordinates,coords,sizeof(coords),cudaMemcpyHostToDevice));
 for(bool linear:{false,true}){resource.res.array.array=transferArray;desc.filterMode=linear?cudaFilterModeLinear:cudaFilterModePoint;desc.readMode=cudaReadModeElementType;desc.addressMode[0]=cudaAddressModeClamp;cudaTextureObject_t transfer;CHECK(cudaCreateTextureObject(&transfer,&resource,&desc,nullptr));for(float shift:{0.f,.25f}){transferProbe<<<1,8>>>(coordinates,output,volume,transfer,shift,8);CHECK(cudaGetLastError());float actual[32];CHECK(cudaMemcpy(actual,output,sizeof(actual),cudaMemcpyDeviceToHost));float maxError=0;for(int i=0;i<8;i++){double u=double(coords[i])+double(128)/255*shift,p=u*4-(linear?.5:0),f=p-floor(p);int index=int(floor(p));for(int c=0;c<4;c++){auto at=[&](int j){return values[std::max(0,std::min(3,j))*4+c];};double expected=linear?at(index)*(1-f)+at(index+1)*f:at(index);float error=fabsf(actual[i*4+c]-float(expected));maxError=fmaxf(maxError,error);if(!std::isfinite(actual[i*4+c])||error>.005f){printf("FAIL filter=%d shift=%g i=%d channel=%d\n",linear,shift,i,c);return 1;}}}printf("%s shift=%g PASS native paired textures; max error %.9g\n",linear?"linear":"nearest",shift,maxError);}CHECK(cudaDestroyTextureObject(transfer));}
 CHECK(cudaFree(coordinates));CHECK(cudaFree(output));CHECK(cudaDestroyTextureObject(volume));CHECK(cudaFreeArray(volumeArray));CHECK(cudaFreeArray(transferArray));return 0;}
