import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {compile} from '../src/compiler/compiler.js';import {executeCPU} from '../src/compiler/cpu-oracle.js';import {kernelSource} from '../src/sandbox/import.js';
const source=fs.readFileSync(new URL('type-aliases.cu',import.meta.url),'utf8');
test('Value aliases resolve byte casts, constructors, vectors and helper templates',()=>{const a=compile(source,{workgroupSize:[1]}),out=new Uint32Array(4);executeCPU(a,{out},{},[1]);assert.deepEqual([...out],[4,6,5,4]);});
test('Kernel template entry accepts a declared type alias',()=>{const a=compile('typedef float Scalar;template<typename T> __global__ void k(T* out){out[0]=T(3.0);}',{entry:'k<Scalar>',workgroupSize:[1]}),out=new Float32Array(1);executeCPU(a,{out},{},[1]);assert.equal(out[0],3);});
test('Alias state is local to each parse and invalid aliases reject',()=>{compile('typedef float Scalar;__global__ void k(Scalar* out){}');assert.throws(()=>compile('__global__ void k(Scalar* out){}'),/Unsupported type/);for(const alias of ['typedef float* P;','typedef const float C;','typedef void V;','typedef int float;','typedef float A;typedef int A;'])assert.throws(()=>compile(alias+'__global__ void k(){}'));});
test('Desktop import keeps transitive type dependencies and drops unrelated host structures',()=>{const desktop='#include <cuda_runtime.h>\nstruct Host {cudaArray* array;};\ntypedef unsigned short Unused;\ntypedef unsigned char Byte;\ntypedef Byte Value;\nstruct Item {Value channel;};\n__global__ void k(uint* out){Item item;item.channel=(Value)260;out[0]=item.channel;}';const imported=kernelSource(desktop);assert.ok(imported.extracted);assert.ok(!imported.source.includes('cudaArray'));assert.ok(!imported.source.includes('Unused'));assert.ok(imported.source.includes('typedef Byte Value;'));const a=compile(imported.source,{workgroupSize:[1]}),out=new Uint32Array(1);executeCPU(a,{out},{},[1]);assert.equal(out[0],4);assert.equal(imported.source.split('\n').length,desktop.split('\n').length);assert.equal(imported.source.indexOf('__global__'),desktop.indexOf('__global__'));});
test('Used unsupported host-like structures stay visible and fail honestly',()=>{assert.throws(()=>compile(kernelSource('#include <cuda_runtime.h>\nstruct Host {cudaArray* array;};\n__global__ void k(){Host item;}').source),/Unsupported type/);});

test('Alias names cannot silently override values or declarations outside their scope',()=>{for(const body of ['__global__ void k(){int Scalar=1;}','__global__ void k(int Scalar){}','__device__ int Scalar(){return 1;}__global__ void k(){}'])assert.throws(()=>compile('typedef float Scalar;'+body),/shadow a type alias/);assert.throws(()=>compile('__global__ void k(float* out){out[0]=Later(2);}typedef float Later;'),/Unknown|Unsupported/);});
