import {seedBuffer} from '../src/sandbox/config.js';
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {compile} from '../src/compiler/compiler.js';import {executeCPU} from '../src/compiler/cpu-oracle.js';import {packScalars} from '../src/runtime/runtime.js';import {vectorByteScalars as scalars} from './vector-byte-arguments-gpu.js';
const source=readFileSync(new URL('./vector-byte-arguments.cuh',import.meta.url),'utf8'),artifact=compile(source,{workgroupSize:[128,1,1]});
test('Packed byte pointers retain stride one and read across word boundaries through helper offsets',()=>{assert.equal(artifact.metadata.bindings[0].stride,1);assert.equal(artifact.metadata.bindings[0].readOnly,true);assert.match(artifact.wgsl,/b_input: array<u32>/);const input=Uint8Array.from({length:259},(_,i)=>(i*37+11)&255),output=new Uint32Array(1028),positions=new Float32Array(1028);executeCPU(artifact,{input,output,positions},scalars,[3]);for(let i=0;i<257;i++){assert.equal(output[i*4],input[i+1]);assert.equal(output[i*4+1],input[i+2]);assert.equal(output[i*4+2],56);assert.equal(output[i*4+3],(-9)>>>0);assert.deepEqual([...positions.slice(i*4,i*4+4)],[(i&7)*.125+1.75,((i>>3)&3)*-.5-3.25,((i>>5)&31)*2+3.5,-4.5]);}});
test('All float/int/uint vector sizes use individually packed scalar components',()=>{for(const type of ['float','int','uint'])for(const size of [2,3,4]){const a=compile('__global__ void k('+type+size+' p,'+type+'* out){out[0]=p.x;}');assert.deepEqual(a.metadata.scalars.map(x=>x.name),'xyzw'.slice(0,size).split('').map(c=>'p.'+c));assert.deepEqual(a.metadata.scalars.map(x=>x.offset),Array.from({length:size},(_,i)=>i*4));}});
test('Invalid vector components reject transactionally instead of truncating',()=>{for(const [key,value]of [['pair.x',-1],['pair.y',4294967296],['edge.w',2147483648],['edge.x',.5],['spacing.x',Infinity],['weights.w',1e40]]){const target=new ArrayBuffer(artifact.metadata.uniformSize);new Uint8Array(target).fill(123);assert.throws(()=>packScalars(artifact.metadata,{...scalars,[key]:value},target));assert.ok(new Uint8Array(target).every(v=>v===123));assert.throws(()=>executeCPU(artifact,{input:new Uint8Array(259),output:new Uint32Array(1028),positions:new Float32Array(1028)},{...scalars,[key]:value},[3]));}});
test('Const byte writes including helper writes and vector parameter mutation remain rejected',()=>{for(const s of ['__global__ void k(const uchar* a){a[0]=1;}','__device__ void put(uchar* p){p[0]=2;} __global__ void k(const uchar* a){put(a);}','__global__ void k(float3 p){p.x=2;}','__global__ void k(float3 p){p=make_float3(1,2,3);}'])assert.throws(()=>compile(s));});
test('Dual host/device helper qualifiers retain device code and reject host-only functions',()=>{for(const qualifiers of ['__host__ __device__','__device__ __host__']){const a=compile('inline '+qualifiers+' float3 lerp(float3 a,float3 b,float t){return a+t*(b-a);} __global__ void k(float3 a,float3 b,float* out){out[0]=lerp(a,b,.5f).x;}');assert.match(a.wgsl,/fn f_lerp/);}for(const s of ['__host__ float host(){return 0;}','__host__ __global__ void k(){}'])assert.throws(()=>compile(s));});

test('Sandbox byte inputs allocate packed records instead of widened floats',()=>{const data=seedBuffer(artifact.metadata.bindings[0],{records:259,fill:'ramp'});assert.ok(data instanceof Uint8Array);assert.equal(data.byteLength,259);assert.equal(data[258],2);});
