// MIT validation host. Included NVIDIA device functions retain their BSD notice.
#include <cuda_runtime.h>
#include <helper_math.h>
#include <cstdio>
#include <vector>
#include <algorithm>
#include "volume-render.cuh"
#define CHECK(x) do{auto e=(x);if(e!=cudaSuccess){printf("CUDA ERROR %s\n",cudaGetErrorString(e));return 2;}}while(0)
int main(){std::vector<unsigned char> volumeData(32768);FILE* file=fopen("showcases/volume-render/Bucky.raw","rb");if(!file||fread(volumeData.data(),1,volumeData.size(),file)!=volumeData.size())return 2;fclose(file);cudaArray_t volumeArray,transferArray;auto volumeChannel=cudaCreateChannelDesc<unsigned char>(),transferChannel=cudaCreateChannelDesc<float4>();CHECK(cudaMalloc3DArray(&volumeArray,&volumeChannel,make_cudaExtent(32,32,32)));cudaMemcpy3DParms copy={};copy.srcPtr=make_cudaPitchedPtr(volumeData.data(),32,32,32);copy.dstArray=volumeArray;copy.extent=make_cudaExtent(32,32,32);copy.kind=cudaMemcpyHostToDevice;CHECK(cudaMemcpy3D(&copy));const float transfer[]={0,0,0,0,1,0,0,1,1,.5f,0,1,1,1,0,1,0,1,0,1,0,1,1,1,0,0,1,1,1,0,1,1,0,0,0,0};CHECK(cudaMallocArray(&transferArray,&transferChannel,9,1));CHECK(cudaMemcpy2DToArray(transferArray,0,0,transfer,sizeof(transfer),sizeof(transfer),1,cudaMemcpyHostToDevice));cudaResourceDesc resource={};resource.resType=cudaResourceTypeArray;resource.res.array.array=volumeArray;cudaTextureDesc desc={};desc.normalizedCoords=1;desc.filterMode=cudaFilterModeLinear;desc.readMode=cudaReadModeNormalizedFloat;for(int i=0;i<3;i++)desc.addressMode[i]=cudaAddressModeClamp;cudaTextureObject_t volume,table;CHECK(cudaCreateTextureObject(&volume,&resource,&desc,nullptr));resource.res.array.array=transferArray;desc.readMode=cudaReadModeElementType;CHECK(cudaCreateTextureObject(&table,&resource,&desc,nullptr));
 for(int scenario=0;scenario<3;scenario++){unsigned w=scenario==1?65:128,h=scenario==1?49:128;float matrix[]={1,0,0,0,0,1,0,0,0,0,1,4};if(scenario==2){matrix[0]=.8660254f;matrix[2]=.5f;matrix[8]=-.5f;matrix[10]=.8660254f;matrix[3]=2;matrix[11]=3.4641016f;}CHECK(cudaMemcpyToSymbol(c_invViewMatrix,matrix,sizeof(matrix)));const size_t count=w*h;std::vector<unsigned> result(count+16,0xdeadbeef);std::fill(result.begin(),result.begin()+count,0);unsigned* output;CHECK(cudaMalloc(&output,result.size()*4));CHECK(cudaMemcpy(output,result.data(),result.size()*4,cudaMemcpyHostToDevice));d_render<<<dim3((w+7)/8,(h+7)/8),dim3(8,8)>>>(output,w,h,.05f,1,0,1,volume,table);CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());CHECK(cudaMemcpy(result.data(),output,result.size()*4,cudaMemcpyDeviceToHost));for(size_t i=count;i<result.size();i++)if(result[i]!=0xdeadbeef){printf("FAIL output guard\n");return 1;}unsigned lit=0;for(size_t i=0;i<count;i++)if(result[i]&0xffffff)lit++;if(!lit){printf("FAIL empty image\n");return 1;}char path[128];snprintf(path,sizeof(path),"reports/volume-render-native-%d.bin",scenario);file=fopen(path,"wb");if(!file||fwrite(result.data(),4,result.size(),file)!=result.size())return 2;fclose(file);CHECK(cudaFree(output));printf("scenario=%d %ux%u PASS native original volume renderer, %u lit pixels, output guards intact\n",scenario,w,h,lit);}
 CHECK(cudaDestroyTextureObject(volume));CHECK(cudaDestroyTextureObject(table));CHECK(cudaFreeArray(volumeArray));CHECK(cudaFreeArray(transferArray));return 0;}
