// SPDX-License-Identifier: MIT
#include <cuda_runtime.h>
#include <cstdio>
#include <vector>
#include <cmath>
typedef unsigned int uint;
#include "volume-convert-kernel.cuh"
int main(){FILE* file=fopen("reports/volume-convert-input.bin","rb");if(!file)return 2;fseek(file,0,SEEK_END);long bytes=ftell(file);rewind(file);std::vector<float> input(bytes/4);if(fread(input.data(),1,bytes,file)!=bytes)return 2;fclose(file);std::vector<uint> output(input.size()+16,0xdeadbeef);float* dInput;uint* dOutput;cudaMalloc(&dInput,bytes);cudaMalloc(&dOutput,output.size()*4);cudaMemcpy(dInput,input.data(),bytes,cudaMemcpyHostToDevice);cudaMemcpy(dOutput,output.data(),output.size()*4,cudaMemcpyHostToDevice);conversionProbe<<<(input.size()+63)/64,64>>>(dInput,dOutput,input.size());auto e=cudaMemcpy(output.data(),dOutput,output.size()*4,cudaMemcpyDeviceToHost);cudaFree(dInput);cudaFree(dOutput);if(e!=cudaSuccess)return 2;int roundedDifferences=0;for(size_t i=0;i<output.size();i++){double clamped=i<input.size()?fmin(1.0,fmax(0.0,double(input[i]))):0;uint expected=i<input.size()?uint(clamped*255.0):0xdeadbeef;if(output[i]!=expected){printf("FAIL %zu\n",i);return 1;}if(i<input.size()&&uint(float(clamped)*255.0f)!=expected)roundedDifferences++;}file=fopen("reports/volume-convert-native.bin","wb");if(!file)return 2;fwrite(output.data(),4,output.size(),file);fclose(file);printf("PASS %zu original NVIDIA byte conversions and 16 guards; float-product shortcut differs at %d inputs\n",input.size(),roundedDifferences);
std::vector<float> scaled(255);std::vector<uint> actual(255);for(int i=0;i<255;i++)scaled[i]=float(double(i+1)/65535.0);cudaMalloc(&dInput,255*4);cudaMalloc(&dOutput,255*4);cudaMemcpy(dInput,scaled.data(),255*4,cudaMemcpyHostToDevice);scaleProbe<<<4,64>>>(dInput,dOutput,255);e=cudaMemcpy(actual.data(),dOutput,255*4,cudaMemcpyDeviceToHost);cudaFree(dInput);cudaFree(dOutput);if(e!=cudaSuccess)return 2;for(int i=0;i<255;i++)if(actual[i]!=uint(double(scaled[i])*65535.0))return 1;file=fopen("reports/exact-byte-scale-native.bin","wb");if(!file)return 2;fwrite(actual.data(),4,255,file);fclose(file);printf("PASS 255 double-scale rounding boundaries; float-product shortcut differs at all 255\n");
}
