// SPDX-License-Identifier: MIT
#include <cuda_runtime.h>
#include <helper_math.h>
#include <cstdio>
#include <vector>
#include "volume-filter-kernel.cuh"
#define CHECK(x) do{auto e=(x);if(e!=cudaSuccess){printf("CUDA ERROR %s\n",cudaGetErrorString(e));return 2;}}while(0)
struct Resource{cudaArray_t array;cudaTextureObject_t texture;cudaSurfaceObject_t surface;};
int main(int argc,char** argv){bool bucky=argc>1;int width=bucky?32:8,height=width,depth=bucky?32:4,total=width*height*depth;auto extent=make_cudaExtent(width,height,depth);Resource r[3];auto desc=cudaCreateChannelDesc<unsigned char>();for(auto& v:r){CHECK(cudaMalloc3DArray(&v.array,&desc,extent,cudaArraySurfaceLoadStore));cudaResourceDesc resource={};resource.resType=cudaResourceTypeArray;resource.res.array.array=v.array;CHECK(cudaCreateSurfaceObject(&v.surface,&resource));cudaTextureDesc t={};t.normalizedCoords=1;t.filterMode=cudaFilterModeLinear;t.addressMode[0]=t.addressMode[1]=t.addressMode[2]=cudaAddressModeWrap;t.readMode=cudaReadModeNormalizedFloat;CHECK(cudaCreateTextureObject(&v.texture,&resource,&t,nullptr));}
std::vector<unsigned char> input(total),out(total);for(int i=0;i<total;i++)input[i]=(i*37+11)&255;if(bucky){FILE* file=fopen("showcases/volume-filter/Bucky.raw","rb");if(!file||fread(input.data(),1,total,file)!=total)return 2;fclose(file);}cudaMemcpy3DParms upload={};upload.srcPtr=make_cudaPitchedPtr(input.data(),width,width,height);upload.dstArray=r[0].array;upload.extent=extent;upload.kind=cudaMemcpyHostToDevice;CHECK(cudaMemcpy3D(&upload));
for(int scenario=0;scenario<4;scenario++){for(auto& v:r){CHECK(cudaDestroyTextureObject(v.texture));cudaResourceDesc resource={};resource.resType=cudaResourceTypeArray;resource.res.array.array=v.array;cudaTextureDesc t={};t.normalizedCoords=scenario<2;t.filterMode=scenario==3?cudaFilterModePoint:cudaFilterModeLinear;t.addressMode[0]=t.addressMode[1]=t.addressMode[2]=scenario<2?cudaAddressModeWrap:cudaAddressModeClamp;t.readMode=cudaReadModeNormalizedFloat;CHECK(cudaCreateTextureObject(&v.texture,&resource,&t,nullptr));}float4 weights[125]={};int count=scenario?3:1;weights[0]=scenario?make_float4(-.125f,0,0,.25f):make_float4(0,0,0,1);weights[1]=make_float4(0,.25f,0,.5f);weights[2]=make_float4(.125f,0,.25f,.25f);CHECK(cudaMemcpyToSymbol(c_filterData,weights,sizeof(weights)));for(int pass=0;pass<2;pass++){int src=pass==0?0:1,dst=pass==0?1:2;d_filter_surface3d<<<dim3(width/8,height/8,depth),dim3(8,8,1)>>>(count,scenario?.0625f:0,extent,r[src].texture,r[dst].surface);CHECK(cudaGetLastError());CHECK(cudaDeviceSynchronize());cudaMemcpy3DParms read={};read.srcArray=r[dst].array;read.dstPtr=make_cudaPitchedPtr(out.data(),width,width,height);read.extent=extent;read.kind=cudaMemcpyDeviceToHost;CHECK(cudaMemcpy3D(&read));char path[128];snprintf(path,sizeof(path),"reports/volume-filter-%snative-%d-%d.bin",bucky?"bucky-":"",scenario,pass);FILE* file=fopen(path,"wb");if(!file)return 2;fwrite(out.data(),1,total,file);fclose(file);int different=0;for(int i=1;i<total;i++)if(out[i]!=out[0])different++;printf("scenario=%d pass=%d %d voxels captured, first=%u different-from-first=%d\n",scenario,pass,total,out[0],different);}}
for(auto& v:r){CHECK(cudaDestroyTextureObject(v.texture));CHECK(cudaDestroySurfaceObject(v.surface));CHECK(cudaFreeArray(v.array));}return 0;}
