// Small browser/Node runtime using the ABI generated by the WebShader backend.
export class WasmKernel{
 static async load(base){
  const {default:create}=await import(base+'.mjs');
  const bytes=await fetch(base+'.wasm').then(r=>{if(!r.ok)throw Error('Build the experiment first');return r.arrayBuffer();});
  const abi=await fetch(base+'.abi.json').then(r=>r.json());
  return new WasmKernel(await create({wasmBinary:bytes}),abi);
 }
 constructor(module,abi){this.module=module;this.abi=abi;this.buffers=new Map();}
 buffer(name,view){
  let b=this.buffers.get(name);if(!b||b.bytes!==view.byteLength){if(b)this.module._free(b.ptr);b={ptr:this.module._malloc(view.byteLength),bytes:view.byteLength};if(!b.ptr)throw Error('WASM allocation failed');this.buffers.set(name,b);}
  this.module.HEAPU8.set(new Uint8Array(view.buffer,view.byteOffset,view.byteLength),b.ptr);return b;
 }
 dispatch(groups,values){
  if(groups.length!==3||groups.some(n=>!Number.isInteger(n)||n<1))throw Error('Invalid dispatch dimensions');
  const args=this.abi.params.map(p=>{if(!(p.name in values))throw Error('Missing kernel argument '+p.name);return p.pointer?this.buffer(p.name,values[p.name]).ptr:values[p.name];});
  this.module._cw_dispatch(...groups,...args);
  for(const p of this.abi.params)if(p.pointer&&!p.constant){const b=this.buffers.get(p.name),v=values[p.name];new Uint8Array(v.buffer,v.byteOffset,v.byteLength).set(this.module.HEAPU8.subarray(b.ptr,b.ptr+b.bytes));}
 }
 dispose(){for(const b of this.buffers.values())this.module._free(b.ptr);this.buffers.clear();}
}
