import {decodePGM} from './pgm.js';
import {decodePPM} from './ppm.js';
import {SCAN_SOURCE} from '../runtime/scan-kernels.js';
import {seedBuffer} from './config.js';
const strides={u32:4,i32:4,f32:4,'vec4<f32>':16,cw_uchar:1,cw_uchar4:4};
export function validatePipeline(plan){
 if(!plan||!plan.buffers||!Array.isArray(plan.steps)||!plan.steps.length||plan.steps.length>24)throw Error('A pipeline needs buffer declarations and 1–24 steps.');
 if(Object.keys(plan.buffers).length>32)throw Error('A pipeline supports at most 32 buffers.');let bytes=0;
 for(const [name,s]of Object.entries(plan.buffers)){if(!Object.hasOwn(strides,s?.type)||!Number.isInteger(s.records)||s.records<1||s.records>1048576)throw Error('Invalid pipeline buffer '+name);bytes+=strides[s.type]*s.records;if(!['zero','one','ramp','random','sphere'].includes(s.fill)||s.fill==='sphere'&&s.type!=='vec4<f32>')throw Error('Invalid fill for '+name);}
 if(bytes>64*1048576)throw Error('Pipeline buffers exceed 64 MiB.');
 const control=value=>{if(typeof value==='number'){if(!Number.isFinite(value))throw Error('Pipeline values must be finite.');return;}const s=plan.buffers[value?.buffer],index=value?.index??0,divisor=value?.divideCeil??1;if(!s||s.type!=='u32'||!Number.isInteger(index)||index<0||index>=s.records||!Number.isInteger(divisor)||divisor<1||divisor>1048576)throw Error('A control value needs a uint buffer, valid index and positive divisor.');};
 for(const step of plan.steps){if(step.scan){const s=step.scan,a=plan.buffers[s.source],b=plan.buffers[s.target],t=plan.buffers[s.total];if(!a||!b||!t||[a,b,t].some(x=>x.type!=='u32')||new Set([s.source,s.target,s.total]).size!==3||!Number.isInteger(s.count)||s.count<1||s.count>a.records||s.count>b.records)throw Error('A scan needs distinct uint source, target and total buffers and a valid count.');continue;}
 if(typeof step.entry!=='string'||!Array.isArray(step.block)||step.block.length!==3||step.block.some(n=>!Number.isInteger(n)||n<1)||step.block.reduce((a,b)=>a*b,1)>1024||!Array.isArray(step.groups)||step.groups.length!==3)throw Error('Dispatch steps need an entry, block and groups.');step.groups.forEach(control);Object.values(step.scalars||{}).forEach(control);if(step.skipIfZero!==undefined)control(step.skipIfZero);}
 const p=plan.preview;if(p?.kind==='image'){if(!['rgba8','gray-u8'].includes(p.format)||!(p.format==='gray-u8'?['cw_uchar','cw_uchar4']:['u32']).includes(plan.buffers[p.buffer]?.type)||![p.width,p.height].every(n=>Number.isInteger(n)&&n>0&&n<=4096)||p.width*p.height>plan.buffers[p.buffer].records*(p.format==='gray-u8'&&plan.buffers[p.buffer].type==='cw_uchar4'?4:1))throw Error('Image preview needs bounded dimensions and a matching RGBA8 uint or grayscale byte buffer.');return bytes;}if(p?.kind!=='triangles'||plan.buffers[p.positions]?.type!=='vec4<f32>'||plan.buffers[p.normals]?.type!=='vec4<f32>')throw Error('Triangle preview needs float4 position and normal buffers.');control(p.count);return bytes;
}
export async function executePipeline({plan,source,defines,compiler,runtime,rootArtifact,allocateBuffer,resources,textureResources,onArtifact=()=>{},log=()=>{}}){
 validatePipeline(plan);if(plan.steps.some(s=>s.scan))for(const entry of ['scanBlocks','addScanOffsets'])onArtifact({...((await runtime.kernel(SCAN_SOURCE,{entry,workgroupSize:[256,1,1]})).artifact),sourceLabel:'runtime scan CUDA helper'});const buffers={},prepared=[],cache=new Map();
 const resolve=async value=>{if(typeof value==='number')return value;const key=value.buffer+':'+(value.index??0);if(!cache.has(key))cache.set(key,(await runtime.read(buffers[value.buffer],Uint32Array,4,(value.index??0)*4))[0]);return Math.ceil(cache.get(key)/(value.divideCeil??1));};
 const invalidate=name=>{for(const key of cache.keys())if(key.startsWith(name+':'))cache.delete(key);};
 const fetchLocal=async path=>{const url=new URL(path,location.href);if(url.origin!==location.origin)throw Error('Pipeline data must be on this origin.');const response=await fetch(url);if(!response.ok)throw Error('Pipeline input could not be loaded: '+path);return response;};
 for(const step of plan.steps){if(step.scan){prepared.push(step);continue;}const artifact=step.entry===rootArtifact.name&&String(step.block)===String(rootArtifact.metadata.workgroupSize)?rootArtifact:(await compiler.compile(source,{entry:step.entry,workgroupSize:step.block,defines,sharedMemoryBytes:step.sharedMemoryBytes||0})).artifact;if(artifact.metadata.surfaces?.length)throw Error('Pipeline surface bindings are not enabled.');
 const names=new Set([...artifact.metadata.bindings,...(artifact.metadata.textures||[])].map(b=>b.name));for(const name of Object.keys(step.bindings||{}))if(!names.has(name))throw Error('Unknown pipeline parameter '+name);
 for(const b of artifact.metadata.bindings){const name=step.bindings?.[b.name]??b.name;if(plan.buffers[name]?.type!==b.elementType)throw Error(step.entry+': missing or mismatched buffer '+name);}
 onArtifact(artifact);prepared.push({...step,artifact,kernel:await runtime.kernel(artifact)});
 }
 for(const [name,spec]of Object.entries(plan.buffers)){const data=seedBuffer({elementType:spec.type,stride:strides[spec.type]},spec),custom=allocateBuffer?.(name,spec,data);buffers[name]=custom||runtime.createBuffer(data);if(!custom)resources.push(buffers[name]);}
 let textureBytes=0;for(const [name,spec]of Object.entries(plan.textures||{})){if(buffers[name])throw Error('Duplicate resource '+name);let texture;
 if(spec.kind==='image-u8'){if(!Array.isArray(spec.dimensions)||spec.dimensions.length!==2||spec.dimensions.some(n=>!Number.isInteger(n)||n<1||n>4096))throw Error('Byte image texture needs bounded dimensions.');textureBytes+=spec.dimensions[0]*spec.dimensions[1];if(textureBytes>16*1048576)throw Error('Pipeline textures exceed 16 MiB.');const image=decodePGM(new Uint8Array(await(await fetchLocal(spec.source)).arrayBuffer()));if(image.width!==spec.dimensions[0]||image.height!==spec.dimensions[1])throw Error('Image dimensions do not match texture.');if(spec.filter&&spec.filter!=='nearest'||spec.normalizedCoords===true||spec.addressMode&&spec.addressMode!=='clamp-to-edge')throw Error('Byte images require unnormalized nearest clamp sampling.');texture=runtime.createByteTexture2D(Uint8Array.from(image.data,v=>Math.round(v*255)),{width:image.width,height:image.height});
 }else if(spec.kind==='image-rgba'){if(!Array.isArray(spec.dimensions)||spec.dimensions.length!==2||spec.dimensions.some(n=>!Number.isInteger(n)||n<1||n>4096))throw Error('Image texture needs bounded dimensions.');textureBytes+=spec.dimensions[0]*spec.dimensions[1]*16;if(textureBytes>16*1048576)throw Error('Pipeline textures exceed 16 MiB.');const image=decodePPM(new Uint8Array(await(await fetchLocal(spec.source)).arrayBuffer()));if(image.width!==spec.dimensions[0]||image.height!==spec.dimensions[1])throw Error('Image dimensions do not match texture.');texture=runtime.createTexture2D(image.data,{width:image.width,height:image.height,format:'rgba32float',filter:spec.filter||'nearest',addressMode:spec.addressMode||'clamp-to-edge',normalizedCoords:spec.normalizedCoords});
 }else if(['linear-u32','linear-u8'].includes(spec.kind)){const decoded=spec.values??(spec.encoding==='raw'?Array.from(new Uint8Array(await(await fetchLocal(spec.source)).arrayBuffer())):await(await fetchLocal(spec.source)).json()),values=spec.key?decoded[spec.key]:decoded,max=spec.kind==='linear-u32'?4294967295:255;if(!Array.isArray(values)||!values.length||values.length>1048576||values.some(v=>!Number.isInteger(v)||v<0||v>max))throw Error('Linear texture requires valid integer elements.');textureBytes+=values.length*(spec.kind==='linear-u32'?4:1);if(textureBytes>16*1048576)throw Error('Pipeline textures exceed 16 MiB.');texture=runtime.createLinearTexture(spec.kind==='linear-u32'?Uint32Array.from(values):Uint8Array.from(values));
 }else if(spec.kind==='volume-u8'){if(!Array.isArray(spec.dimensions)||spec.dimensions.length!==3||spec.dimensions.some(n=>!Number.isInteger(n)||n<1||n>2048))throw Error('Volume requires three valid dimensions.');const size=spec.dimensions.reduce((a,b)=>a*b,1);textureBytes+=size;if(textureBytes>16*1048576)throw Error('Pipeline textures exceed 16 MiB.');let data;if(spec.values){if(!Array.isArray(spec.values)||spec.values.some(v=>!Number.isInteger(v)||v<0||v>255))throw Error('Volume needs byte values.');data=Uint8Array.from(spec.values);}else data=new Uint8Array(await(await fetchLocal(spec.source)).arrayBuffer());if(data.length!==size)throw Error('Volume dimensions do not match input.');const [width,height,depth]=spec.dimensions;texture=runtime.createTexture3D(data,{width,height,depth,filter:spec.filter||'nearest',addressMode:spec.addressMode||'clamp-to-edge',normalizedCoords:spec.normalizedCoords});
 }else throw Error('Unknown pipeline texture kind.');buffers[name]=texture;textureResources.push(texture);}
 for(const step of prepared){if(step.scan){const s=step.scan;log('GPU exclusive scan: '+s.source+' → '+s.target+' ('+s.count+' values)');await runtime.exclusiveScan(buffers[s.source],buffers[s.target],{count:s.count,total:buffers[s.total]});invalidate(s.target);invalidate(s.total);continue;}
 if(step.skipIfZero!==undefined&&await resolve(step.skipIfZero)===0){log('Skipped '+step.entry+': zero work items.');continue;}
 const groups=await Promise.all(step.groups.map(resolve));if(groups.some(n=>!Number.isInteger(n)||n<0||n>65535)||groups.reduce((a,b)=>a*b,1)*step.block.reduce((a,b)=>a*b,1)>4194304)throw Error('Resolved pipeline launch exceeds sandbox limits.');const scalars=Object.fromEntries(await Promise.all(Object.entries(step.scalars||{}).map(async([name,value])=>[name,await resolve(value)]))),bindings=Object.fromEntries([...step.artifact.metadata.bindings,...(step.artifact.metadata.textures||[])].map(b=>[b.name,buffers[step.bindings?.[b.name]??b.name]]));
 log('Dispatch '+step.entry+': '+groups.join(' × ')+' blocks');runtime.batch().dispatch(step.kernel.bind(bindings,scalars),groups).submit();for(const b of step.artifact.metadata.bindings)if(!b.readOnly)invalidate(step.bindings?.[b.name]??b.name);
 }
 await runtime.idle();if(plan.preview.kind==='image')return {buffers,count:plan.preview.width*plan.preview.height};const count=await resolve(plan.preview.count);if(!Number.isInteger(count)||count<0||count%3||count>plan.buffers[plan.preview.positions].records||count>plan.buffers[plan.preview.normals].records)throw Error('Triangle count must fit both buffers and be a multiple of three.');return {buffers,count};
}
