import {GpuRuntime} from '../../src/runtime/runtime.js';
import {check} from './check.js';
const [audit,artifacts,verified]=await Promise.all(['../../reports/nvidia-audit.json','./artifacts.json','../../reports/nvidia-gpu.json'].map(async p=>(await fetch(p)).json()));
const $=id=>document.getElementById(id);
$('summary').textContent=`${audit.samples.length} sample directories · ${audit.samples.reduce((n,s)=>n+s.probes.length,0)} compiler probes · ${verified.results.filter(r=>r.pass).length} hardware-verified kernel entries. Upstream ${audit.commit.slice(0,12)}. Search each sample for its actual status.`;
function element(tag,text){const e=document.createElement(tag);e.textContent=text;return e;}
function render(){const q=$('search').value.toLowerCase(),filter=$('filter').value;$('samples').replaceChildren();for(const s of audit.samples){const checks=verified.results.filter(r=>r.sample===s.id&&r.pass);if(q&&!JSON.stringify(s).toLowerCase().includes(q)||filter==='passed'&&!checks.length||filter==='blocked'&&s.browser.status!=='translation-rejected')continue;const card=element('article','');card.append(element('h2',s.name),element('p',s.id),element('p',s.summary),element('p',`Browser: ${checks.length?checks.length+' isolated kernel checks passed on NVIDIA hardware':s.browser.status}`),element('p',`Full native application: ${s.native.status}. ${s.native.reason||''}`));const upstream=element('a','View original NVIDIA source ↗');upstream.href=s.url;card.append(upstream);
 for(const result of checks){const index=artifacts.findIndex(r=>r.sample===s.id&&r.entry===result.entry),row=artifacts[index],p=element('p',result.entry+' · '),link=element('a','Open CUDA / WGSL sandbox ↗');link.href='../../sandbox.html?nvidia='+index;p.append(link);card.append(p);const button=element('button','Run verified fixture'),output=element('pre','');button.onclick=async()=>{button.disabled=true;output.textContent='Requesting GPU → compiling WGSL → uploading inputs → dispatching → reading and checking output…';let runtime;try{runtime=await GpuRuntime.create();const r=await check(row,runtime);output.textContent=JSON.stringify({adapter:runtime.describe(),...r},null,2);}catch(e){output.textContent=e.message;}finally{runtime?.dispose();button.disabled=false;}};card.append(button,output);}
 const details=element('details',''),title=element('summary','Compiler findings and limitations');details.append(title,element('pre',JSON.stringify({browser:s.browser,features:s.features,probes:s.probes},null,2)));card.append(details);$('samples').append(card);}}
$('search').oninput=render;$('filter').onchange=render;render();
